### ISSUE TITLE
ConverseJS Non Amd Message Send Problem‏

### ISSUE THREAD

**Issue by mustafaevcil** [jcbrand/converse.js#539] opened 2016-01-07 13:37 UTC
I download and pull all required files for using non-amd converse on conversejs.org/non_amd.html. Perfectly working chat on local openfire server and configuration is  true. All users login and see contact list. My problem when two roster is typing, all messages not forward. 'client is typing' is shown but message can not send. Bosh session (http-bind) requests  is sending and receiving. When I look session storage, message body not appear , I have messageId. Debug mode can not produced error.

**Comment by jcbrand** [comment] 2016-01-07 18:11
There's not enough information for me to know what the issue is here. You'll need to provide more debug info, also which version you're using and exactly how to reproduce the problem. Otherwise I'll close the ticket.

**Comment by mustafaevcil** [comment] 2016-01-08 07:39
I use latest 0.10.0 version. I share screenshot  of scenario. When my rosters are typing, messages not forward often. Converse detects that write but not show because session storage has not message body.Converse minified version is working successfully. I carried openfire server to outside localhost, same problem is continued.
![messagebody](https://cloud.githubusercontent.com/assets/6851252/12192891/9ca65354-b5eb-11e5-9c67-38d43d25e0e3.png)
![non-amd](https://cloud.githubusercontent.com/assets/6851252/12192892/9ca81cf2-b5eb-11e5-829d-a282bc8b2020.png)

**Comment by mustafaevcil** [comment] 2016-01-08 07:54
![messahewithoutbody](https://cloud.githubusercontent.com/assets/6851252/12193119/d2a781d8-b5ed-11e5-958a-7d87bf2e1faa.png)
![messagewithbody](https://cloud.githubusercontent.com/assets/6851252/12193118/d2a6be60-b5ed-11e5-9850-da468ee2065f.png)

**Comment by pmkaboo** [comment] 2016-01-08 15:51
@mustafaevcil try replacing strophes `getUniqueId` function with something that generates unique ids reliably, before initializing converse, for example: `Strophe.Connection.prototype.getUniqueId = function () { return +new Date(); }`

im not 100% sure yet if its the correct solution, but i also had problems with sent/received messages not appearing in the chatbox even though they were sent and received correctly, and it was because the `getUniqueId` function was generating conflicting ids and the backbone model was then instead of creating new messages just rewriting old messages that had the same id as the incoming messages - after page refresh the old messages were changed to the ones that didnt appear. 
sometimes it could even lead to duplicated messages, probably because of corrupted timestamps.

it was also quite easy to replicate, user A just had to write a bunch of messages to user B, refresh page, and write another bunch of messages to user B. on page refresh the unique id counter got reset, and since both of them already had messages with these ids saved in backbone, they never appeared and just rewrote the old ones.

**Comment by themaverick777** [comment] 2016-01-08 21:29
I had the same problem today with the non amd. While sending message, I noticed that the messages were not being received, while the message counter is incremented. After debugging, it seems the message attribute becomes null in the onMessageAdded() function after sending a chat status. As said above i guess the conflict in msgid might have caused the problem, hence the message not being rendered.

**Comment by jcbrand** [comment] 2016-01-10 15:42
The problem with the (non-)unique message ids should be fixed in 0.10 because it relies on a newer version of Strophe.js (where the problem occured as mentioned by @pmkaboo).

@mustafaevcil Do you have the latest version of strophe.js? If not, then that's likely the problem and upgrading your strophe.js version will likely fix the problem.

**Comment by mustafaevcil** [comment] 2016-01-11 08:20
I change strophe.js  in strophejs-latest.zip and problem is solved. I think non_amd site can use this file, upgrading strophe.js version is fixed thank you for your suggestions.

**Closed** 2016-01-11 08:20 UTC

**Comment by manumklm** [comment] 2016-02-01 11:06
i am also facing some problem with pending_request offline messaging.ie, the person who send the request only get offline message of person who got the request.
