### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'connected' of undefined" with prebound session with keepalive:true

### ISSUE THREAD

**Issue by irek-zaripov** [jcbrand/converse.js#552] opened 2016-01-18 11:16 UTC
We have an error message at line 
https://github.com/jcbrand/converse.js/blob/master/converse.js#L6133 `Uncaught TypeError: Cannot read property 'connected' of undefined`
ControlBoxToggle.Backbone.View.extend.showControlBox	@	converse.js?s=1452857022:43111
ControlBoxToggle.Backbone.View.extend.onClick	@	converse.js?s=1452857022:43128
jQuery.event.dispatch	@	converse.js?s=1452857022:5057
elemData.handle	@	converse.js?s=1452857022:4725

**Comment by jcbrand** [comment] 2016-01-18 12:18
You need to give more information and context. How and when does this happen? The problem needs to be reproducible.

**Comment by irek-zaripov** [comment] 2016-01-18 12:53
The source of problem is in the roundcube's plugin function rcmail_converse_init(converse, args). 
From this function is invoked converse.initialize(args, function(e){ 
    });
Where args = `animate":false,"authentication":"prebind","keepalive":true,"prebind_url":"https://bosh.url.test:7443/http-bind/","allow_registration":false,"allow_contact_requests":false,"allow_contact_removal":false,"expose_rid_and_sid":true,"allow_otr":false,"allow_logout":false,"auto_list_rooms":true,"auto_subscribe":true,"hide_offline_users":false,"auto_reconnect":true,"message_carbons":true,"forward_messages":true,"auto_away":500,"show_controlbox_by_default":false,"roster_groups":true,"prebind":true,"bosh_service_url":"https://bosh.url.test:7443/http-bind/","debug":true,"jid":"operator@bosh.url.test/Roundcube-569cd9f8f34d2","sid":"561a2926","rid":8483394132,"i18n"...`
args.jid args.rid args.sid are set in prebind call, XMPP server shows the status:
'operator	Roundcube-569cd9f8f34d2	Local	Authenticated	User is connected via SSL	**Offline**'
GET https://bosh.url.test:7443/http-bind/
jQuery.ajaxTransport.options.send	@	converse.min.js?s=1452857022:10099
jQuery.extend.ajax	@	converse.min.js?s=1452857022:9644
converse.initialize.callback.startNewBOSHSession	@	converse.min.js?s=1452857022:43149
converse.initialize.callback.attemptPreboundSession	@	converse.min.js?s=1452857022:43191
converse.initialize.callback.initConnection	@	converse.min.js?s=1452857022:43248
converse.initialize.callback._initialize	@	converse.min.js?s=1452857022:43286
converse.initialize	@	converse.min.js?s=1452857022:43352
API.initialize	@	converse.min.js?s=1452857022:43376
rcmail_converse_init	@	converse-rcmail.js?s=1453114063:16
(anonymous function)	@	?_task=mail:410
main	@	converse.min.js?s=1452857022:314
(anonymous function)	@	converse.min.js?s=1452857022:388

**Comment by irek-zaripov** [comment] 2016-01-18 12:58
After this clicking the `Toggle chat` lead to the previous error.

**Comment by jcbrand** [comment] 2016-01-18 14:21
Originally you showed output with indicated that you're using an unminified converse.js file, now you give output that has converse.min.js.

So there's a difference in the two cases.

I'm not sure what the problem is here. In `initConnection` the connection is set up and assigned to the global `converse` variable. I see that it gets called in the second stacktrace that you pasted. But again, in that stacktrace it mentions converse.min.js and in the first stacktrace it mentions converse.js, so I don't know if I can trust it.

Best you can do is to set a breakpoint in the place just before the error occurs. Then with your browser's JS debugger you can move up the call stack and inspect different values.

You can also put a breakpoint in the `initConnection` method and see what happens there.

**Comment by irek-zaripov** [comment] 2016-01-20 11:27
OK @jcbrand, thanks for hints!
But I think `"keepalive":true` should increase the performance of converse.js for roundcube plugin, am I right?
But with this option we get an `"Could not restore session for jid: operator@bosh.url.xxx/Roundcube- Error message: _restore: no restoreable session."`
_if (this.keepalive) {
                if (!this.jid) {
                    throw new Error("initConnection: when using 'keepalive' with 'prebind, you must supply the JID of the current user.");
                }
                try {
               **return this.connection.restore(this.jid, this.onConnectStatusChanged);**_  // there we get an error `"Could not restore session for jid: operator@bosh.bngf.ru/Roundcube- Error message: _restore: no restoreable session."`
                _} catch (e) {
                    converse.log("Could not restore session for jid: "+this.jid+" Error message: "+e.message);
                }
            } else { // Not keepalive
                if (this.jid && this.sid && this.rid) {
                    return this.connection.attach(this.jid, this.sid, this.rid, this.onConnectStatusChanged);
                } else {
                    throw new Error("initConnection: If you use prebind and not keepalive, "+
                        "then you MUST supply JID, RID and SID values");
                }
            }_

**Comment by jcbrand** [comment] 2016-01-20 11:44
Strictly speaking, that's not an error, it's a log entry and it's completely normal.
If converse.js cannot restore BOSH session from tokens in sessionStorage (which is what the `keepalive` option does), then it logs that message.

The user should then either log in manually (because there's no existing session to restore) or converse.js can be configured in various ways to log the user in automatically (for example the `prebind_url` option).

**Comment by irek-zaripov** [comment] 2016-01-20 11:52
>If converse.js cannot restore BOSH session from tokens in sessionStorage (which is what the keepalive option does), then it logs that message.

But I stil can't get, should restoring BOSH session from tokens in sessionStorage increase the performance?

**Comment by jcbrand** [comment] 2016-01-20 12:26
It immediately resumes an existing BOSH session instead of taking multiple seconds to establish a new BOSH session. So yes, it makes it quicker.

**Comment by irek-zaripov** [comment] 2016-01-20 12:34
Thanks @jcbrand !
I'd like to update the version of converse.js to 10.x.x in roundcube plugin with support of `keepalive: tue`

**Comment by jcbrand** [comment] 2016-01-20 12:43
That would be great @irek-zaripov 

I'm going to make a new release soon, I just want to find a solution for #555

**Closed by jcbrand** 2016-01-20 12:43 UTC
