### ISSUE TITLE
Offline and Logout states do not properly update once users start chatting

### ISSUE THREAD

**Issue by mhchu** [jcbrand/converse.js#632] opened 2016-04-13 07:36 UTC
The problem: In our chat client testing, we have discovered that when two users begin to chat, user status of offline or logged out does not properly reflect on the other user's roster. For example, prior to messaging each other, both users accurately see user status changes (to away, dnd, back to online, offline, online, logged out). However, after sending messages to each other, offline and logged out status do not show up on the other user's roster. (Sometimes after the user comes back online they cannot message each other.) I have verified by inspecting network traffic in Chrome and Firefox that presence type="unavailable" is received but no change occurs in the contact list / roster. (In addition, there is no message in the chat box stating that "User X is offline".) Once this problem manifests, it continues to persist unless I log out of both users and refresh the page to log them back in OR close my chat window tabs and open fresh tabs.

The setup: I have different users M and T both running latest release version of converse.js 0.10.1.
converse is set to auto_login:true, authentication: 'login', and jid and password set in converse.initialize() call. With this setup, refreshing the page logs the respective user in. For each test case, I opted to start with fresh tabs and repeated each sequence three times to ensure it was not an intermittent bug:

Works:
- Fresh tabs: M goes offline; T sees M offline; M goes online; T sees M online; M logs out; T sees M offline; M refreshes page to log back in; T sees M online

Does not work properly:
- Fresh tabs: M sends T a message (T does not send M a message); M goes offline; T still sees M online
- Fresh tabs: M sends T a message (T does not send M a message); M logs out; T still sees M online
- Fresh tabs: M sends T a message (T does not send M a message); M sets status to away; T sees M as away (and away message appears in chatbox); M logs out; T still sees M as away; M refreshes to log back in and contact list is missing M; M changes state to online (T sees M online); Messages from T do not get received by M
- Fresh tabs: M sends T a message (T does not send M a message); T goes offline; M still sees T online
- Fresh tabs: M sends T a message (T does not send M a message); T logs out; M still sees T online
- Fresh tabs: M sends T a message (T does not send M a message); T logs out; M still sees T online; T refreshes to log back in and contact list appears to be fine; T changes state to away (M sees no state change in T); T messages M (M receives message)

How to "reset" so status is properly reflected again:
Best Way: Fresh tabs or browsers for both users
Seems to work just as well: Log both users out; refresh both pages
Does not work: clearing sessionStorage and refreshing

We were hoping to launch chat with converse.js on our site this week, but this could be a showstopper issue for us as users could be confused (or worse, upset) that they believe the other user is online while they are chatting and the messages never get through.

Thanks! (P.S. This is an impressive project! The more I look into it, the more I realize how complex chat is - bravo to jcbrand and all those that contributed to this project. Converse is quite an accomplishment!)

**Comment by mhchu** [comment] 2016-04-13 07:56
Also, this might be related (or not), but if a user is in a MUC room and goes "offline" then comes back "online" their messages are not seen in the MUC room. (Typing in a MUC room does not appear to cause roster updates to fail when the user goes offline or logout.)

**Comment by jcbrand** [comment] 2016-04-13 08:16
Thanks for the detailed bug report.

I have removed the option to go "offline" in the master branch of converse.js, because the way it's currently presented in converse.js doesn't fit the semantics of the XMPP spec.

"Offline" is not a valid chat state (the valid states are "online", "chatty", "dnd", "away", "xa"). According to the XMPP spec going offline actually means logging out, you can't go offline while remaining logged in, and the fact that converse.js supported the idea that you can change your status to offline while still being logged in caused various problems for people (similar to what you report).

You can read #547 for more info on this.

For people who absolutely need the offline status and only use converse.js (no other XMPP clients are used), you could perhaps repurpose the `xa` (extended away) status to behave as an `offline` status. In other words, to show `offline` instead of `extended away` in all of the UI. This would require some customization, a plugin for it could be written.

> Also, this might be related (or not), but if a user is in a MUC room and goes "offline" then comes back "online" their messages are not seen in the MUC room. (Typing in a MUC room does not appear to cause roster updates to fail when the user goes offline or logout)

I'm not sure whether this is related.

You might want to try the master branch of converse.js to see whether it helps, but like I mentioned, it removes the `offline` state entirely. The master branch is by now relatively stable. I intend to make a new release soon (as soon as time permits).

**Comment by mhchu** [comment] 2016-04-13 09:31
Thanks for the quick response! Sorry, I wasn't clear in my bug report, but we tested both offline and log out and the behavior is the same. I just retested the scenarios that were creating problems with converse intialization setting of include_offline_state=false (just in case that setting was causing a problem) and am seeing the same problem:
- Confirmed that without chatting, M setting status (away, dnd) and logging off properly reflect on T's converse roster
- Fresh tabs: M sends T a message (T does not send M a message); M logs out; T still sees M online
- Fresh tabs: M sends T a message (T does not send M a message); M sets status to away; T sees M as away (and away message appears in chatbox); M logs out; T still sees M as away; M refreshes to log back in and contact list is fine; M changes state to online (T sees M online); M changes state to away (T sees M away); M logs off (T continues to see M as away [not logged off]).
I confirmed that I am still receiving <presence type="unavailable"> on T's browser.

I will take a look at the current master branch tomorrow. We were afraid to use the master branch because you mentioned the refactoring occurring on the master in #620 and last week I saw the master had failed the Travis CI build. I see the current master branch has passed and am excited to hear it is relatively stable. Thanks!

**Comment by mhchu** [comment] 2016-04-13 18:36
Just tested on the latest master branch from this morning and getting the same problem: as soon as a user sends a chat message to another user, that other user no longer sees when the first user goes offline. Confirmed that a <presence type="unavailable" /> was received by the client but no apparent action was taken to update the roster or set a message in the chatbox that the user has logged off.

**Comment by theclifbar** [comment] 2016-04-14 04:36
Hi, I just wanted to chime in with an important addition: 
_If user 1 messages with user 2, and user 1 closes their browser/tab or crashes out, user 2 will never see user 1's status update; user 1 will always appear as online._

This is in line with mhchu's report earlier, but has nothing to do with offline/log out.  It's as if status updates are ignored once a conversation is started.

From a user perspective, this is killer as there will be a lot of hurt feelings as user 2 may continue to send messages or feel ignored even though user 1 logged out, crashed, or ran out of batteries hours ago.

Once user 1's heartbeat pings go missing after 1 minute, debugging shows ejabberd sending the appropriate stanzas to user 2's converse.js client, but the status update is ignored.  (We've confirmed that updates happen on other xmpp clients, so it's not ejabberd).

JC and team, if you have any hints to where this code lives and any known pitfalls, we'd be happy to fix it in master and make a pull request.

**Comment by mhchu** [comment] 2016-04-15 08:17
After additional testing, it looks like this bug occurs when authentication is set to "login" but not when using "prebind". I loaded a blank page with converse.js and initialization set to only:
```javascript
converse.initialize({
	bosh_service_url: 'https://<my ejabberd server>:<my port>/http-bind',
	authentication: 'login',
});
```
And after two users sent messages to each other, if one user logs out or closes their window, the other user never updates the roster or provides a chat message referencing the other user's offline state. I confirmed the ```<presence type="unavailable" />``` was received.

This probably does not appear to occur when using authentication:'prebind', so we are moving forward using 'prebind'.

**Comment by jcbrand** [comment] 2016-04-15 09:17
I'd be a bit surprised if it makes a difference whether `authentication` is set to `login` or `prebind`. I'm not sure what the issue is here so I can't really point you to a particular snippet of code.

This is something that I'd have to replicate and debug, to get to the bottom of.

**Comment by systemidx** [comment] 2016-08-09 14:47
Has there been any movement on a fix for this?

**Comment by jcbrand** [comment] 2016-08-09 14:51
@systemidx no, have you experienced the same behavior?

**Comment by systemidx** [comment] 2016-08-09 15:04
@jcbrand Thanks for the quick response! 

Yes, we are noticing this behavior as well. We are using `login` and not `prebind`. I believe we are using version 1.0.0. We are having a fair amount of difficulty reproducing this on a consistent basis, but if we can provide any information that you think may be pertinent, please let me know!

**Comment by jcbrand** [comment] 2016-08-09 15:18
The main issue for me is time. I'm guessing it would take a few hours to hunt down and fix this bug.

**Comment by systemidx** [comment] 2016-08-09 15:29
I got some more information on how this was replicated by our QA department. It seems like just a bunch of logging in and out between two users (who are each others' rosters) and a lot of message stanzas between the two.

We *have* verified that when the issue is reproduced that the presence stanza DOES get sent to the affected user, however, it does not get acted upon (to our knowledge).

**Comment by chrisuehlinger** [comment] 2016-08-09 16:41
I work at the same place as @systemidx, the bug report initially filed by @mhchu describes our problem exactly (although we only allow users to logout, not set their status to offline).

I've done some debugging in chrome and found the error to happen around this line: https://github.com/jcbrand/converse.js/blob/master/src/converse-core.js#L1149

I set a breakpoint at that line and checked the list of resources in both the working and buggy cases. 

In the working case (when the users haven't talked to each other), there is only one resource (the one which is about to be removed).

In the buggy case, there is often a long list of resources like this: `["converse.js-11677418", "converse.js-33485953", null, "converse.js-25586398", "converse.js-63272723", "converse.js-53325575", "converse.js-88881490", "converse.js-55035741", "converse.js-67605170", "converse.js-32776429", "converse.js-92344671", "converse.js-54184931"]`

My hunch is that these are old dead sessions that didn't log out properly (i.e. closed the browser window without logging out or crashed). Is there something we should do differently to handle those kinds of sessions?

**Comment by jcbrand** [comment] 2016-08-09 17:39
Thanks for the extra info.

> My hunch is that these are old dead sessions that didn't log out properly 

Yes, I think that's what's happening.

Assuming this is the case (which it most likely is), the question then becomes whether converse.js can be informed once a resource becomes stale. I think the assumption is that eventually the XMPP server will send a presence of type unavailable for a stale resource (e.g. when the user closed the browser), and then the code you linked to will execute and the resource will be removed from the list.

So one of two things is happening here... (1) either the unavailable presences are being sent but converse.js doesn't pick them up, or (2) they're not being sent out.

Both hypotheses need to be tested, perhaps you can help there? If you set `debug: true` when calling `converse.initialize`, then you'll see all the stanza traffic between the XMPP server and converse.js. So you'll be able to check which presences are received, for example when the other user reloads the page, or when they close their browser.

**Comment by chrisuehlinger** [comment] 2016-08-09 17:53
When a user closes their tab, we don't get a presence update immediately, but we get one a couple minutes later. If the users haven't been talking to each other (which is what seems to trigger the bug in this thread) the UI updates accordingly.

Also, we've been logging the stanzas this whole time, and converse is always receiving `<presence type="unavailable">` stanzas when users log out by clicking our "Log out" button. The issue is that sometimes, after receiving this stanza, the roster UI does not update to show them unavailable.

Since I knew that we were receiving the stanzas, I used the Chrome DevTools breakpoint debugger to step through `presenceHandler()` and sort out why the roster wasn't updating. The answer is in my previous comment: when two users have been talking to each other, the list of resources is really long, and probably contains some long dead sessions.

**Comment by chrisuehlinger** [comment] 2016-08-09 18:33
I think I've found the issue, maybe this will help:

We use the `converse-mam` plugin to retrieve archived messages when a user opens a Chatbox with someone they've talked to before. When `converse-mam` retrieves the messages, many of them are from old sessions (and therefore are from resources that no longer exist). These old resources get added to the contact's list of resources. This would seems to be where things go wrong.

I've attached a copy of the stanza we get back when we ask for archived messages. I've changed our domain to example.com, but otherwise left it unchanged. Note the different resource IDs on messages from the same user:

[archived-messages.txt](https://github.com/jcbrand/converse.js/files/409659/archived-messages.txt)

**Comment by chrisuehlinger** [comment] 2016-08-09 19:14
@jcbrand: Quick gut check, do you think there would be any problems if we scrubbed the resource IDs of all archived messages and then told the `onMessage()` method not to add `null` resources to the list?

**Comment by jcbrand** [comment] 2016-08-10 08:05
> We use the converse-mam plugin to retrieve archived messages when a user opens a Chatbox with someone they've talked to before. When converse-mam retrieves the messages, many of them are from old sessions (and therefore are from resources that no longer exist). These old resources get added to the contact's list of resources. This would seems to be where things go wrong.

Brilliant work.

So the bug appears to be that JID resources from archived messages are added to the list of "connected/online resources", which of course is wrong, since receiving an archived message is no indication that the sender (i.e. resource) of that message is currently online.

I grepped the code, and I think this is the place where the resource gets added wrongly:
https://github.com/jcbrand/converse.js/blob/561c138edd825917112c8e40c71d7c3ff0addc55/src/converse-core.js#L1379

I'm inclined to say that the list of online resources should only be populated when a presence is received and *not* when a message is received. Either that, or there must be a check to determine whether the message received is an archived message.

Concerning `null` resources, I'm not sure how they get added, that's not desired behavior, probably they get added in the same place, since there's no check whether there is actually a resource.

I think the solution is to simply remove the line I linked to above (and the lines earlier in the function where `resource` is assigned). Could you please check whether this solves things for you?

**Comment by chrisuehlinger** [comment] 2016-08-12 18:11
Sorry for the delay. We've tested this solution on our end and it worked well. Our fork of converse has diverged enough that I wouldn't feel comfortable submitting an upstream change. However I will say that our only change was to remove that one line.

**Comment by jcbrand** [comment] 2016-08-12 19:46
Thanks for the update and the help on this @chrisuehlinger. I've made the necessary change.

**Closed** 2016-08-12 19:45 UTC
Labels: bug
