### ISSUE TITLE
Old chat windows hanging around

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#328] opened 2015-03-09 13:34 UTC
When the ConverseJS session timesout, I observed that the Login Panel comes up. However, the Chat Windows remain open..I want to CLOSE ALL the Open Chat Windows  (Chat rooms and Chat boxes) if any, whenever the Login Panel shows up. 

Where and how can I achieve this one ?

**Comment by jcbrand** [comment] 2015-03-09 13:50
IMHO this is desired. You don't want to lose your chat messages because the client disconnected.
Ideally the client should be able to just reconnect again, but last I checked there were some issues with that.

What you want to do is listen for some kind of event for when there was a disconnect. I'm not sure whether there is such an event, I don't think so, but you might want to look in the Strophe.js code to double check.

It's then a matter of listening to that event and then using the converse API to close all chat boxes.

I'm going to close this ticket, because this is more a support request and not a bug report or feature request. Support questions should go to the mailing list.

**Comment by gpadbidri** [comment] 2015-03-13 20:02
Hi JC,

I think there was a BUG with the CloseAllChatBoxes () Code (as the comment in converse.js also mentions "// Should always resolve, but shit happens" says)...

I was not able to diagnose the <code>close()-> this.model.destroy()</code> , but I have observed that although there are views available, they are not accessible since View MODEL is not sequentially removed, hence at any given point in time NOT ALL chat windows would close. I think just reversing the array worked for me : 

<code>
closeAllChatBoxes: function (include_controlbox) {
                var i, chatbox;
		  // Below For Loop added by Gauri
		  if(this.model.models.length > 0){
		  for(var cnt = this.model.models.length -1; cnt >= 0 ; cnt--){
 			var id = this.model.models[cnt].get('id');
			if (include_controlbox || id !== 'controlbox') {
                        if (this.get(id)) { // Should always resolve, but shit happens
                            this.get(id).close();
                        }
                    }
		  }
		  }
                return this;
            }
</code>

Please let me know if the above code made sense ? Thanks !

**Comment by jcbrand** [comment] 2015-03-16 11:38
It's true that sometimes the views don't have models attached to them anymore and then calling ``close`` doesn't work.

Why do you think it works if you reverse the array?

**Comment by jcbrand** [comment] 2015-03-16 11:40
Another thing...

I think ``closeAllChatboxes`` should actually call ``close`` on the views and not the models. The view should then check if it has a model and delegate it to the model, otherwise it should simply hide the DOM element.

**Closed** 2015-03-21 22:47 UTC
