### ISSUE TITLE
After deactivating OTR, chat window still shows encryption messages

### ISSUE THREAD

**Issue by lovetox** [jcbrand/converse.js#638] opened 2016-04-28 18:18 UTC
![unbenannt](https://cloud.githubusercontent.com/assets/8661218/14896480/3bec7af8-0d7e-11e6-96a2-af06704f81bd.PNG)

OTR is deativated, if i clear the chat, close the window and reopen it again, it always shows these messages again.

adding and removing the account doesnt work also

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/33435630-after-deactivating-otr-chat-window-still-shows-encryption-messages?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by rasos** [comment] 2016-05-23 06:41
Same issue here with repeating messages about generating key or key exchange. Is a show blocker.

**Comment by PegasusGo** [comment] 2016-08-25 17:24
Hello lovetox  , can you add me on skype please : neozak7
I will pay you to integrate conversejs in my website

**Comment by smitbose** [comment] 2017-03-04 15:56
@jcbrand I cannot reproduce this bug. I created two accounts and attempted enabling and disabling of encryption. Although it shows a little bit latency, but eventually it comes through. I was able to carry out both encrypted and unencrypted conversations. 

@lovetox can you please tell the exact steps for reproducing this bug? I'm sorry that I can't understand the exact problem.

**Comment by lovetox** [comment] 2017-03-04 22:01
i tried, and cannot reproduce it at the moment. but its almost a year, so maybe this was fixed unintentionally by something else.

**Comment by smitbose** [comment] 2017-03-05 06:00
So I think this issue should be marked as closed now?

**Closed** 2017-03-05 09:36 UTC
Labels: bug, gsoc-teaser
