### ISSUE TITLE
Offline status does not update Roster

### ISSUE THREAD

**Issue by ajinkyac** [jcbrand/converse.js#487] opened 2015-09-28 11:23 UTC
Steps to reproduce:
Assume that there are two users (user1 & user2) that are already subscribed to each other.

1.) Change the XMPP status of user2 to Offline
2.) The contact in user1's roster doesn't update and remains to be in the last known XMPP state (anything other than offline)

RosterContacts::presenceHandler has a check, 
...
else if (presence_type === 'unavailable' && contact) {
                    // Only set the user to offline if there aren't any
                    // other resources still available.
                    if (contact.removeResource(resource) === 0) {
                        contact.save({'chat_status': "offline"});
                    }
                }

The contact here has some resources (sometimes its null and contact default resource or something else).
Does bypassing the check for resources and changing the status to offline create some problem?

**Comment by jcbrand** [comment] 2015-09-28 12:24
No, it doesn't break anything, but it doesn't really make sense to show the user as offline if they are still online one some other device.

Are you saying that converse.js has other resources saved for that user which aren't valid?

**Comment by ajinkyac** [comment] 2015-09-28 12:32
I am debugging this more too. The resource list was intermittent in its contents e.g. I was logged on only from once single browser instance and this one time it showed me 3 items in resource list out of which one was identifiable as the the number generated by Math.floor(Math.random()*139749825) attached to the JID. Rest two resources were unknown to me.

For now I am setting the state to offline irrespective of the resources, I'll keep this bug posted if I find sometime more. Or you may close it as invalid or worksforme.

**Comment by jcbrand** [comment] 2015-09-28 12:54
I've had other people complain before that setting someone to offline doesn't "work".

An underlying bug might be that resources aren't cleared properly, so zombie resources hang around.

You win the internet if you can figure out what the underlying issue is here ;)

**Comment by jcbrand** [comment] 2016-01-15 09:06
I tried and am unable to replicate this issue, so I'll close it now.

If you find a way to replicate the problem reliably, please reopen and explain how.

**Closed by jcbrand** 2016-01-15 09:06 UTC

**Comment by rlanvin** [comment] 2016-01-18 15:04
I'm continuing the conversation from #550. I am able to replicate the issue reliably, so thanks to @jcbrand guidance I did some debugging and here is the problem:

* Initial status: User A is connected with Converse.js. User B is connected with the resource "Pidgin", and no other. Converse.js sees it and properly display the status as "available"
* User A (Converse.js) gets disconnected (see #550 on how to reproduce this step). User B "Pidgin" signs off after Converse.js is disconnected. Therefore Converse.js misses the message from the server that the resource "Pidgin" for User B is unavailable. But "Pidgin" is still stored internally in the list of resources for User B in Converse.js.
* User A (Converse.js) re-connects. Converse.js receives the following statement:

```
<presence xmlns="jabber:client" type="unavailable" to="userA@test.dev/test" from="userB@test.dev"/>
```

Note that since User B is now completely offline, the statement doesn't include a resource. Therefore, the following code is not triggered, because `resource` is `null`:

```
                    if (contact.removeResource(resource) === 0) {
                        contact.save({'chat_status': "offline"});
                    }
```

The resource "Pidgin" is never removed, and the contact is never displayed offline.

I believe in `removeResource()` there should be a test, if `resource` is null then the `resources` array for this user is emptied, so any remaining "ghost" resource is nuked. What do you think?

**Comment by jcbrand** [comment] 2016-01-18 15:30
@rlanvin Great work! I think you found the bug. Will you please make a pull request with the proposed change?

**Comment by devurandom** [comment] 2016-04-06 10:05
I believe to still see this issue. I am using v0.10.1 with Roundcube 1.2_beta and the latest version of its converse plugin (priyadi/roundcube-converse.js-xmpp-plugin@787190abd7d529827d5f533184f6a619cf8ad343 from September 2014) with following config:
```php
$rcmail_config['converse_jsfile'] = 'converse.nojquery.min.js';
$rcmail_config['converse_config'] = array(
        'message_archiving' => 'roster',
        'message_carbons' => true
);
```

**Comment by devurandom** [comment] 2016-04-06 12:52
I forked the Roundcube XMPP plugin into [devurandom/roundcube-converse.js-xmpp-plugin](https://github.com/devurandom/roundcube-converse.js-xmpp-plugin), incorporated selected parts of lixmal/roundcube-converse.js-xmpp-plugin@d3bf3866710a1e8fce42f091244747830d017c3f (as well as some unrelated patches by @gekoraus) and updated to converse.js 0.10.1. Now offline state is displayed correctly.
