### ISSUE TITLE
Converse not fully connecting when using prebind_url

### ISSUE THREAD

**Issue by rlanvin** [jcbrand/converse.js#550] opened 2016-01-15 16:41 UTC
Hello,

I'm trying to use `prebind_url` (with `authentication` set to `prebind` and `keepalive` set to true) with Converse 0.10 and Prosody 0.9. Basically, the issue is that it's not fully connecting. Here is the description of what is happening exactly:

- `prebind_url` is called, a valid json is returned with jid, sid and rid (HTTP 200, Content-Type application/json).
- The chatbox opens. However, everybody appears offline, and the roster is not the latest version. Prosody's log at this point show the prebinded session with status "Unavailable" and a message along the line of "BOSH session marked as inactive for 60s".
- The browser log shows the following 3 lines (with debug enabled)

> Could not restore session for jid: test@test.dev Error message: _restore: no restoreable session.
> Status changed to: ATTACHED
> Attached

There is nothing else.

- If I do something within those 60 seconds, such as manually setting the status to "online", then I'm connected. Prosody's log show the session with status "Available", and Converse starts to communicate with the server, as shown in the browser's log. If however, I idle for 60s, anything I try to do will eventually result in "Status changed to: CONNFAIL", and the chat being disconnected.

So it looks like Converse.js is not fully connected after prebind_url has been called. I found similar issues such as #65 but the fix doesn't work for me.

**Comment by jcbrand** [comment] 2016-01-15 20:20
> `BOSH session marked as inactive for 60s`

I might be wrong, but I think that's the issue.

The message `no restorable session` is normal and not an error when you're loading the page for the first time. So I think that can be ignored.

I googled a bit for the top error and found these links:
https://groups.google.com/forum/#!topic/candy-chat/EIxG0_w3Yi8
http://lists.jitsi.org/pipermail/dev/2014-May/020779.html
https://github.com/otalk/stanza.io/issues/43

**Comment by rlanvin** [comment] 2016-01-15 21:50
So do you think the issue might come from Prosody? According to the logs, prebinding seems to work fine, but after the JSON object with jid/rid/sid is returned, Converse is not talking to Prosody at all, (unless I do something manually, such as changing my status) and therefore the session expires after 60s of inactivity. What should be the behavior? I can paste more logs if you think it's necessary.

**Comment by jcbrand** [comment] 2016-01-16 05:41
>   but after the JSON object with jid/rid/sid is returned, Converse is not talking to Prosody at all

So you don't get your contacts roster?

**Comment by rlanvin** [comment] 2016-01-16 08:57
Indeed. To be precise: Converse shows an old version of the roster, i.e. contacts that have been added or removed recently are not shown, and the presence status is also outdated.

I did more tests today and I believe I narrowed down the problem. Here is a way I can reliably reproduce the bug:

1. First, on a fresh browser tab, I go to my test page. The prebinding **works fine**, Converse is connected and get the contact roster.
2. Then, still on the same tab I navigate away (to another website for example)
3. After some time (over 1 minute), I come back to my test page, **still using the same browser tab**. Converse shows "Disconnected" 
4. I reload the page, and then the bug happens. Converse calls prebind_url again, but then it shows the old roster with the old presence from step 1 - however it is **not** connected and **not** talking to Prosody.

Here are the logs:

At step 2 (while navigating away), on Prosody

    BOSH client inactive too long, destroying session at 1452934032
    Destroying session for test@test.dev/mywebsite (test@test.dev): BOSH client silent for over 60 seconds
    Received[c2s]: <presence type='unavailable'>

At step 3 (when coming back), on Prosody:

    BOSH body open (sid: 778568ab-b478-42b0-8f8b-ae3f9dcd550c)
    Client tried to use sid '778568ab-b478-42b0-8f8b-ae3f9dcd550c' which we don't know about

At step 3, on Converse:

```
Status changed to: ATTACHED
Attached
1 no requests during idle cycle, sending blank request
0 _throttledRequestHandler called with 1 requests
0 request id 1.0 posting
0 request id 1.0 state changed to 1
<body rid=​"1107970663" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"778568ab-b478-42b0-8f8b-ae3f9dcd550c">​</body>​
0 request id 1.1 state changed to 2
0 request id 1.1 state changed to 3
0 request id 1.1 state changed to 4
0 removing request
0 _throttledRequestHandler called with 0 requests
0 request id 1 should now be removed
0 request id 1.1 got 200
1 _dataRecv called
<body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" type=​"terminate" condition=​"item-not-found">​</body>​
Status changed to: CONNFAIL
1 _doDisconnect was called
Status changed to: DISCONNECTED
```

Then at step 4, Converse shows the logs from my first message.

**Comment by jcbrand** [comment] 2016-01-18 07:30
>  Converse calls prebind_url again

Are you 100% sure this is the case? If so, then your prebind service is returning old or simply invalid SID and RID tokens, which is why Prosody says:

> Client tried to use sid '778568ab-b478-42b0-8f8b-ae3f9dcd550c' which we don't know about

Another thing that might perhap be happening is that when you reload the page (after coming back), Converse.js tries to reuse the SID and RID tokens that it finds in sessionStorage (due to the `keepalive` feature).

These tokens used to be valid, but are now expired, so Prosody rejects them.

If that is what's happening (which I think is likely), then strophe.js needs to be updated to clear the tokens from sessionStorage when disconnection happens.

**Comment by rlanvin** [comment] 2016-01-18 11:24
> Are you 100% sure this is the case?

Yes, and the SID and RID are new and valid as far as I can tell. To clarify: prebind_url is not called on the first page load after coming back, only on subsequent page loads.

> Another thing that might perhap be happening is that when you reload the page (after coming back), Converse.js tries to reuse the SID and RID tokens that it finds in sessionStorage

Indeed I think you are right. However this is not the issue I'm having right now (though maybe it's what's causing it). Of course it would be nice if Converse.js would attempt to reconnect automatically, but I can live with a "Disconnected" message. The real issue is that when I try to reload the page to get Converse.js to reconnect, it doesn't work (it does calls prebind_url but then fail to talk to Prosody, unless I do something manually before the timeout).

At the moment, the only way I found to solve the problem when it happens is to close to browser tab, and reopen a new one, which indeed seems to indicate that the issue is related to sessionStorage.

Let me know if you need me to do more tests.

**Comment by jcbrand** [comment] 2016-01-18 12:14
Well, if prebind_url is called after you reload the page, then the cause can't be what I thought it might be (sessionStorage cached tokens). In that case, then I'd assume the problem lies with your prebind service and the tokens it returns. I don't have any other theory in that case.

The crux of the matter is this log message from Prosody:
> Client tried to use sid '778568ab-b478-42b0-8f8b-ae3f9dcd550c' which we don't know about

Either an invalid SID is returned from your prebind service, or an invalid (expired) SID is taken from sessionStorage. If you're sure that your prebind service gets called, then it must be returning an invalid SID for some reason.

> Let me know if you need me to do more tests.

Well, you can try the following. Log in and then make a note of the SID value that's included in the XMPP stanzas sent and received from the XMPP server. Each stanza will have it included as an attribute to the `body` tag. The SID is the session ID, so it'll stay constant for the whole session.

Then, reproduce the problem (be navigating to different site and then going back and reloading the page) and check what the value of the SID is then, whether it's the same as the original or not.

**Comment by rlanvin** [comment] 2016-01-18 12:29
Sorry if I wasn't clear, but the message "Client tried to use sid..." only happens when I come back after some time of inactivity, and results in Converse.js being disconnected - which is the expected behavior I think. *At this point prebind_url is not yet called*. Only *after* I reload the page in an attempt to reconnect Converse.js does the prebind_url get called - again, this is the expected behavior I think. The issue is that now, Converse.js is not properly connected to the server.

Just to make sure, I did the test you asked. Here are the results:

1. First page load on a fresh tab (where everything is working fine) : SID `2bc90f68-da4b-43db-ab05-491f8474cfa7`
2. When coming back after some time browsing another site (enough time for Prosody to kill the connection): `Client tried to use sid '2bc90f68-da4b-43db-ab05-491f8474cfa7' which we don't know about`
3. I refresh the page, hoping that Converse.js will now reconnect
4. `prebind_url ` i called and correctly returns a new, different SID: `{"jid":"test@test.dev\/test","sid":"c351b8ea-e340-4413-9797-1f67c41e2d0a","rid":1345198062}`
5. The chatbox opens, but the roster is outdated, and Converse.js is not talking to the server

The issue is really only at the last step, otherwise everything seems to work as it should. Could there be some cached variables that aren't properly cleared when a disconnect happens? Maybe that could cause the reconnect to not work properly (just guessing here).

**Comment by jcbrand** [comment] 2016-01-18 12:48
Ok, thanks for clarification. Now it's clearer to me.

I think what is likely happening is that converse.js isn't sending out a presence stanza after step 3, which explains the non-activity until you do something manually.

This is probably the same kind of problem as described in #536, although I'm not sure what the exact mechanism is in this case.

I recently fixed that issue, but the fix is not released yet. Could you make a checkout of the master branch and test against that? I think my fix for #536 might fix your issue as well.

**Comment by rlanvin** [comment] 2016-01-18 13:24
Alright, I tested with the master and it is much better, thank you! I didn't realize is was related to this other ticket, but I can confirm that your fix works for my issue.

However, there seems to still be a little issue with the roster and presence status not being updated after re-connection, i.e. the presense is "stuck" to what is was before. For example, here is one way to reproduce the problem:

1. Connect to Converse.js, and connect another user with another XMPP client so that you have one "available" user on your roster
2. Browse away so that you get disconnected from Converse by timeout (as explained above)
3. In the meantime, disconnect the other client
4. Come back to Converse.js and reconnect it (as explained above). The other user *still* appears "online". Connecting/Disconnecting the other XMPP client won't change the status of the user on Converse.js.

The server *does* correctly send the presences to Converse.js (I can see it in the logs), but it seems either Converse.js is ignore it, or the UI is not refreshing.

To confirm, Converse.js is receiving this:

```
<presence xmlns="jabber:client" type="unavailable" to="test@test.dev/test" from="anotheruser@test.dev"/>
```

and yet "anotheruser@test.dev" is still shown "available" on the UI.

Any input of this? Do you think it's a different issue?

**Comment by jcbrand** [comment] 2016-01-18 14:26
> Any input of this? Do you think it's a different issue?

Yes, I think it's related to #487.

Take a look at this code:
https://github.com/jcbrand/converse.js/blob/226e2e910d46bfa900cc8caa9e210cdcb3230c73/converse.js#L4677

A roster contact will only be set to offline if all their resources (in other words, all their clients) are set to offline. So if there's one other resource available, then that means the user is still available with one client somewhere.

Since something like this was reported before, there might be a subtle bug somewhere, or perhaps that one user was also logged in with a different XMPP client somewhere else.

If you're sure the user wasn't logged in anywhere else, then you can put a breakpoint in that piece of code and see what happens there.

**Comment by jcbrand** [comment] 2016-01-18 14:28
I'm going to close this issue now, since the original problem is resolved. Concerning the other problem of the stuck presence state, please comment on #487 if you find more details on that. You can also reopen that issue if need be.

**Closed by jcbrand** 2016-01-18 14:28 UTC

**Comment by AndriusA** [comment] 2016-04-22 13:31
had an issue with fairly similar symptoms using the current Master code and Ejabberd, and the issue turned out to be outside of converse.js but maybe useful for somebody with similar problems: accounts get automatically registered by the backend and in some cases the usernames had capital letters in them, resulting in users not being able to add such contacts (resource not available), but also from another xmpp client (Messages) not receiving contact requests.

The latter is more peculiar in that contact requests are received and rendered on Safari but not on Chrome, though on Safari you can't successfully response to them either.

Fixed by translating all usernames to lowercase.
