### ISSUE TITLE
Picking wrong resource for status determination

### ISSUE THREAD

**Issue by badfiles** [jcbrand/converse.js#610] opened 2016-03-09 18:48 UTC
Two users are in mutual subscription and in one another's roster.

User one has logged in twice: first time with resource `alpha`, and now he is in `extendend away` or just `away`, so priority is `0`. After a while he has logged in with resource `beta`, priority `50`, status `online`.
I start js client with the second user, and I see the first one is `away`, but messages come to `beta` resource. I change `beta`'s status to `dnd`, and js client gets notified correctly. Then I change `beta`'s status to `online`, notification is correct again. Then I reload the page with js client and I see user one is `away` again.

It does not happen if the second user is on libpurple client, status is picked up from appropriate resource.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/31721704-picking-wrong-resource-for-status-determination?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

<bountysource-plugin>

**Comment by jcbrand** [comment] 2017-02-20 09:41
This is a duplicate of #785. Will be handled in that ticket.

**Closed by jcbrand** 2017-02-20 09:41 UTC
Labels: bug
