### ISSUE TITLE
 XEP 136 Offline XMPP support

### ISSUE THREAD

**Issue by fpietrosanti** [jcbrand/converse.js#78] opened 2013-10-27 08:47 UTC
It would be very nice if converse would support (maybe it already does) offline XMPP functionalities with store and forward.

With this functionality in place, it would be possible to add OpenPGP encryption functionalities like described at http://xmpp.org/extensions/xep-0027.html that's the only way to exchange securely messages with offline capabilities (OTR require the two peers to be always online).

**Comment by fpytloun** [comment] 2015-05-28 15:11
This seems to be a duplicate of https://github.com/jcbrand/converse.js/issues/306

**Comment by jcbrand** [comment] 2015-05-29 08:10
@fpytloun You're right. I'll close this one.

**Closed by jcbrand** 2015-05-29 08:10 UTC
Labels: enhancement

**Comment by princevg** [comment] 2016-05-28 03:10
@jcbrand Hi I want to integrate the chat to a website which needs offline message support and messahe archiving. Currently archiving with MUC working fine for one to one chat it is not ok
