### ISSUE TITLE
Reconnect does NOT update Roster

### ISSUE THREAD

**Issue by gauripadbidri** [jcbrand/converse.js#429] opened 2015-06-23 13:45 UTC
Steps to reproduce :

1. Initialize Converse Object as follows : 
 converse.initialize({
                       auto_list_rooms: true,
                       auto_subscribe: false,
                       bosh_service_url: BOSH_URL,
                       hide_muc_server: false,
                       i18n: locales.en,
                       prebind: true,
                       prebind_url:'/api/prebind',
                       play_sounds: true,
                       show_controlbox_by_default: true,
                       roster_groups: false,
                       keepalive: true,
                       allow_muc: true,
                       message_carbons:true,
                       auto_reconnect: true
                   });
2. On successful login, try to restart Ejabberd Service (this would disconnect the current session)
3. As Auto reconnect is ENABLED and prebind_url fetches the JID, SID and RID (incremented by 1) from the server, we should be able to login automatically. 
4. Note : Roster is NOT updated and the ones that were online in the roster (but got offline as the session was disconnected) still appear online.

**Comment by annando** [comment] 2015-10-24 15:46
I second this bug report. When "keepalive" is selected the roster will get out of sync when - for example - the computer was sent to sleep for some time. Then only a complete logout helps.

**Comment by ser** [comment] 2015-10-28 14:23
There is a much worse scenario for it  :-1: - this bug is still in the newest 0.9.6.

When keepalive is set, and you are inside a MUC room, the room member list is being cleared every time you click to an other page :(

**Comment by jcbrand** [comment] 2015-10-28 14:49
@ser what you're describing has nothing to do with this ticket and would be a completely different bug. Please make a new ticket for it.

**Comment by ser** [comment] 2015-10-28 14:53
OK, I was sure it is the same, I am creating a new ticket, then. Cheers.

**Comment by jcbrand** [comment] 2016-01-12 05:25
I'm pretty sure this is a duplicate of #536. Closing this ticket in favor of that one.

**Closed by jcbrand** 2016-01-12 05:25 UTC
Labels: bug
