### ISSUE TITLE
Autojoin Chatrooms

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#293] opened 2014-12-18 13:28 UTC
It would be nice if you could autojoin Chatrooms. Its nice for Websites with support rooms or community rooms for example.

**Comment by gbonvehi** [comment] 2015-01-23 12:53
@c143 @jcbrand This can be done using a plugin if needed, here's an example: https://gist.github.com/gbonvehi/376078bd6b702255a7e7

**Comment by gbonvehi** [comment] 2015-01-23 15:26
This could be marked as a duplicate of Auto-connect to room? #156

**Comment by jcbrand** [comment] 2015-01-24 13:02
yep, looks like it. Closing.

**Closed by jcbrand** 2015-01-24 13:02 UTC
Labels: duplicate, enhancement
