### ISSUE TITLE
Converse.js sometimes disable store message archive in ejabberd via set "never" in archive_prefs table

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#798] opened 2017-03-04 04:03 UTC
I have use ejabberd 16.09 server with enabled XEP-0136 MAM and different clients. All message history is stored in ejabberd database and retrieve normally without problems.

But after I use Converse.js I see that new my message history stops saving. After looking at database, I see that in archive_prefs there are new setting "never" for my nickname with timestamp near the time when I use Converse.js service.

I remove this setting, but it give back after some time, so I delete it many times already. And it adds only when I use Converse.js, when I use other Jabber clients long time - it never adds.

Seems that Converse.js sometimes set this setting. Can you describe in which situation can Converse.js add this setting and how to disable this?

**Comment by jcbrand** [comment] 2017-03-06 08:16
I think this is a dupe of #486 which has been fixed.

Can you check if this is still a problem with the 3.0.0 release?

**Closed** 2017-03-07 10:29 UTC
