### ISSUE TITLE
XEP-0363: HTTP File Upload

### ISSUE THREAD

**Issue by kruks23** [jcbrand/converse.js#466] opened 2015-09-07 07:19 UTC
Hi,

It would be nice if converse.js implements XEP-0363: HTTP File Upload to share files:
http://xmpp.org/extensions/xep-0363.html

Sharing files in this way is very easy because you upload a file to your server and then you share the url. 

Conversations and gajim implement this XEP.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26496343-xep-0363-http-file-upload?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F194169&utm_medium=issues&utm_source=github).

**Comment by Mrfuyu** [comment] 2016-10-07 18:36
This [XEP-0363](http://xmpp.org/extensions/xep-0363.html) is so useful for todays communication. Would be fantastic great to use this with converse.js!

**Comment by jcbrand** [comment] 2016-10-08 19:48
Yes, but it will probably still take a while. I expect to be able to implement this in the coming months.

**Comment by jcbrand** [comment] 2016-11-14 12:43
Duplicate of #161

**Closed by jcbrand** 2016-11-14 12:43 UTC
Labels: enhancement

**Comment by shravanteegala** [comment] 2017-04-26 11:55
How i Can implement the my IOSXMPPClient This XEP-0363 Module.
Please give me sample example.
in objective-c or swift.

**Comment by RafalxM** [comment] 2017-11-21 22:38
Hi  @jcbrand 
I would like to ask about  image send / file upload. 
Are there any chances that this was implemented?
Thank you.

**Comment by jcbrand** [comment] 2017-11-22 08:13
@RafalxM It's on the roadmap, but not yet done.

**Comment by Agostin** [comment] 2017-12-07 16:09
Hello there!  Excuse me @jcbrand what about _file sharing feature_ into chat? Has been added to Converse.js? Thanks

**Comment by jcbrand** [comment] 2017-12-11 08:53
@Agostin See #161
