### ISSUE TITLE
The status restored from sessionStorage is never updated.

### ISSUE THREAD

**Issue by irek-zaripov** [jcbrand/converse.js#555] opened 2016-01-19 09:54 UTC
If users A & B were `online` and had in roster contacts each other, and both closed the all XMPP sessions, the statuses are stored in browser's sessionStorage. After some timeout XMPP server forgets the sessions of users A & B.
If user A will log in to the converse.js again the status of contact B will be restored from the sessionStorage and will never updated to `offline` from XMPP server.

**Comment by irek-zaripov** [comment] 2016-01-19 09:59
>If user A will log in to the converse.js again the status of contact B will be restored from the sessionStorage and will never updated to offline from XMPP server.
This statement is not correct, because of if user will log in and logout, the status will change to the `offline`

**Comment by jcbrand** [comment] 2016-01-19 10:01
This will be fixed with this pull request: https://github.com/jcbrand/converse.js/pull/554

**Comment by irek-zaripov** [comment] 2016-01-19 10:08
I have tested by
$ git clone https://github.com/rlanvin/converse.js
The bug is still present in this pull request. It depends from the sessionStorage restore.

**Comment by jcbrand** [comment] 2016-01-19 12:51
@irek-zaripov In your example above, did you manually log out, or did you close the tab or navigate to a different address?

I think the solution here is to make sure that the cached JID resources are cleared properly when a session is ended. As far as I know, this already happens when you log out manually, but I don't think it'll happen when the tab is closed, or when the user navigates to a different website.

I think one additional fix we need is to clear the JID resources when a BOSH session cannot be restored.

**Comment by irek-zaripov** [comment] 2016-01-20 05:48
@jcbrand thanks for your hints.
In my case with openfire XMPP server the condition
 >// Only set the user to offline if there aren't any
 >// other resources still available.
 >                   **if (contact.removeResource(resource) === 0)** {
  >                      contact.save({'chat_status': "offline"});
 >                   }

is false in any case even when I close the Pidgin client normally or even when set Pidgin client offline manually, because of I have an resource "Roundcube-5698c3fdb1522" which is restored from sessionStorage:
41170  removeResource: function (resource) {  `resource = "PC"`
41171   var resources = this.get('resources'), idx;  `resources = ["Roundcube-5698c3fdb1522", "PC"], idx = undefined`
41172               if (resource) { `resource = "PC"`
41173               idx = _.indexOf(resources, resource); `idx = undefined, resources = ["Roundcube-5698c3fdb1522", "PC"]`
41174                 if (idx !== -1) {
41175                  resources.splice(idx, 1); `resources = ["Roundcube-5698c3fdb1522", "PC"]`
41176                  this.save({'resources': resources});
41177            }
41178      }
41179      else {
41180   // if there is no resource (resource is null), it probably
41181   // means that the user is now completely offline. To make sure
41182   // that there isn't any "ghost" resources left, we empty the array
41183    this.save({'resources': []});
41184    return 0;
41185   }
41186   return resources.length; `resources = ["Roundcube-5698c3fdb1522", "PC"]`

>I think one additional fix we need is to clear the JID resources when a BOSH session cannot be restored.

Yes, may be to empty resources after  fetching from sessionStorage?

**Comment by irek-zaripov** [comment] 2016-01-20 06:17
The resource  "Roundcube-5698c3fdb1522" is a "ghost" resource, because of this session is closed a long time ago in the XMPP server.

**Comment by jcbrand** [comment] 2016-01-20 06:58
Thanks for the debug info. I think I have a relatively good idea of what the problem is here.

> Yes, may be to empty resources after fetching from sessionStorage?

No, not every time, because when `keepalive` is used and we reload the page we don't receive a list of connected resources againg, so we need to rely on what is saved in sessionStorage.

However, we need to make sure that sessionStorage gets cleared at the right times.

- When a user logs out
- When a user gets disconnected
- When converse.js tries to reconnect and fails (because the SID, JID tokens are expired).

**Comment by irek-zaripov** [comment] 2016-01-20 13:01
@jcbrand After cleaning the sessionStorage I can't repeat the bug with updated converse.js!

**Comment by irek-zaripov** [comment] 2016-01-20 13:05
May be because of I'v changed the resource without uniq addition... I'l try later...

**Comment by irek-zaripov** [comment] 2016-01-20 13:29
Without unig addition to the resource the bug is repeated, sorry.

**Comment by jcbrand** [comment] 2016-01-20 13:31
What do you mean with "unique addition"?

**Comment by irek-zaripov** [comment] 2016-01-21 03:33
$resource_prefix = "Roundcube-"; // Resource Name = $resource_prefix+uniqid()

**Comment by irek-zaripov** [comment] 2016-01-21 08:42
@jcbrand , regarding:
> when keepalive is used and we reload the page we don't receive a list of connected resources again

Could you give a hint, where in the code it is done?

**Comment by jcbrand** [comment] 2016-01-21 09:19
We use [Backbone.browserStorage](https://github.com/jcbrand/Backbone.browserStorage) to store the Backbone objects in sessionStorage.

And the connected resources are stored as an attribute of the RosterContact Backbone object. When you reload the page, that entire object is restored from sessionStorage, including its attributes (like resources).

The reason we don't get the list of connected resources again (from the XMPP server) is because we already received them earlier and we are still in the same session (and we're not sending out a presence stanza again).

**Comment by irek-zaripov** [comment] 2016-01-21 10:06
Thanks @jcbrand 
I think, this bug can be referenced to the roundcube plugin bug.
Because of us I discovered, when user logs out there is called converse.clearSession();
https://github.com/jcbrand/converse.js/blob/master/converse.js#L751

**Comment by jcbrand** [comment] 2016-01-21 11:57
Yes, sounds like a fix is needed in the roundcube plugin.

 However, I think there is one edge-case, where it might happen that the resources don't get cleared.

When keepalive attempts to restore a session and fails (because for example the tokens are expired), then it doesn't clear the sessionStorage.

Once I find some time again, I'll add that change and check if I find other areas where the session should be cleared.

Then I'll make the next release.

**Closed** 2016-02-06 09:24 UTC
Labels: bug

**Comment by devurandom** [comment] 2016-04-06 10:43
> I think, this bug can be referenced to the roundcube plugin bug.

Which roundcube plugin bug are you referring to?

> But in roundcube plugin logout call to the converse.js is not implemented.
>
> ------
> 
> Yes, sounds like a fix is needed in the roundcube plugin.

Has this been fixed already?

**Comment by jcbrand** [comment] 2016-04-06 13:11
@devurandom roundcube integration isn't handled in this issue tracker and doesn't fall under this project.

**Comment by devurandom** [comment] 2016-04-06 13:25
I understand that, but you were talking about some bug from which you wanted to refer to this issue. I cannot find that bug.

**Comment by jcbrand** [comment] 2016-04-06 13:32
I don't know whether that bug has ever been reported or what its issue tracker/number would be.
