### ISSUE TITLE
When attempting anonymous login with Openfire, SASL EXTERNAL is used instead of SASL ANONYMOUS

### ISSUE THREAD

**Issue by akrherz** [jcbrand/converse.js#743] opened 2016-12-08 20:37 UTC
Attempting to setup anonymous login of converse.js with Openfire 4.1 (development build).  Discussing the debug log with @jcbrand , he noted 
```
(02:32:57 PM) jcbrand: So converse.js is choosing SASL EXTERNAL instead of ANONYMOUS
(02:33:08 PM) jcbrand: That's a bug
```

Here's the debug console logs
```
Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
converse.js:27390 Warning: The "initialized" event has been deprecated and will be removed, please use "connected".
converse.js:27390 Could not restore session. Error message: _restore: no restoreable session.
converse.js:27390 Status changed to: CONNECTING
converse.js:27390 _throttledRequestHandler called with 1 requests
converse.js:27390 request id 1.0 posting
converse.js:27390 request id 1.0 state changed to 1
converse.js:27390 <body rid="1168519415" xmlns="http://jabber.org/protocol/httpbind" to="laptop.local" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>
converse.js:27390 request id 1.1 state changed to 2
converse.js:27390 request id 1.1 state changed to 3
converse.js:27390 request id 1.1 state changed to 4
converse.js:27390 removing request
converse.js:27390 _throttledRequestHandler called with 0 requests
converse.js:27390 request id 1 should now be removed
converse.js:27390 request id 1.1 got 200
converse.js:27390 _connect_cb was called
converse.js:27390 <body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="laptop.local" authid="11i3tqzwck" sid="11i3tqzwck" secure="true" requests="2" inactivity="30" polling="5" wait="60" hold="1" ack="1168519415" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism><mechanism>CRAM-MD5</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>JIVE-SHAREDSECRET</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>
converse.js:27390 _throttledRequestHandler called with 0 requests
converse.js:27390 _throttledRequestHandler called with 1 requests
converse.js:27390 request id 2.0 posting
converse.js:27390 request id 2.0 state changed to 1
converse.js:27390 <body rid="1168519416" xmlns="http://jabber.org/protocol/httpbind" sid="11i3tqzwck"><auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="EXTERNAL">bGFwdG9wLmxvY2Fs</auth></body>
converse.js:27390 request id 2.1 state changed to 2
converse.js:27390 request id 2.1 state changed to 3
converse.js:27390 request id 2.1 state changed to 4
converse.js:27390 removing request
converse.js:27390 _throttledRequestHandler called with 0 requests
converse.js:27390 request id 2 should now be removed
converse.js:27390 request id 2.1 got 200
converse.js:27390 _dataRecv called
converse.js:27390 <body xmlns="http://jabber.org/protocol/httpbind" ack="1168519416"><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure></body>
converse.js:27390 Status changed to: AUTHFAIL
converse.js:27390 Status changed to: DISCONNECTING
converse.js:27390 Disconnect was called because: Authentication Failed
converse.js:27390 _sendTerminate was called
converse.js:27390 _throttledRequestHandler called with 1 requests
converse.js:27390 request id 3.0 posting
converse.js:27390 request id 3.0 state changed to 1
converse.js:27390 <body rid="1168519417" xmlns="http://jabber.org/protocol/httpbind" sid="11i3tqzwck" type="terminate"/>
converse.js:27390 request id 3.1 state changed to 2
converse.js:27390 request id 3.1 state changed to 3
converse.js:27390 request id 3.1 state changed to 4
converse.js:27390 removing request
converse.js:27390 _throttledRequestHandler called with 0 requests
converse.js:27390 request id 3 should now be removed
converse.js:27390 request id 3.1 got 200
converse.js:27390 _dataRecv called
converse.js:27390 <body xmlns="http://jabber.org/protocol/httpbind" type="terminate" ack="1168519417"/>
converse.js:27390 _doDisconnect was called
converse.js:27390 Status changed to: DISCONNECTED
converse.js:27390 DISCONNECTED
```

Thank you.

**Comment by badfiles** [comment] 2017-01-12 21:12
Connecting to openfire is almost impossible -- external method is always chosen.
Is there a workaround?

**Comment by jcbrand** [comment] 2017-01-13 07:02
Yes, the workaround is mentioned in #751 

And I think this ticket is pretty much a duplicate of #751.

I'll come up with a way to disable SASL-EXTERNAL or reduce it's priority in the next release.

**Closed** 2017-01-15 10:21 UTC
Labels: bug
