### ISSUE TITLE
Converse js 2.0.4 + openfire 4.1.1 not login user

### ISSUE THREAD

**Issue by proton5000** [jcbrand/converse.js#753] opened 2017-01-11 13:03 UTC
converse js 2.0.4 debug

```
converse.min.js:244 Status changed to: CONNECTING
converse.min.js:244 _throttledRequestHandler called with 1 requests
converse.min.js:244 request id 1.0 posting
converse.min.js:244 request id 1.0 state changed to 1
converse.min.js:244 <body rid="153712195" xmlns="http://jabber.org/protocol/httpbind" to="ip-172-31-32-69.us-west-2.compute.internal" xml:lang="en" wait="60" hold="1" content="text/xml; charset=utf-8" ver="1.6" xmpp:version="1.0" xmlns:xmpp="urn:xmpp:xbosh"/>
converse.min.js:244 request id 1.1 state changed to 2
converse.min.js:244 request id 1.1 state changed to 3
converse.min.js:243 XHR finished loading: POST "https://ec2-54-213-237-72.us-west-2.compute.amazonaws.com:7443/http-bind/".
c @ converse.min.js:243
_processRequest @ converse.min.js:243
_throttledRequestHandler @ converse.min.js:243
_connect @ converse.min.js:242
connect @ converse.min.js:242
connect @ converse.min.js:257
authenticate @ converse.min.js:257
dispatch @ converse.min.js:237
g.handle @ converse.min.js:237
converse.min.js:244 request id 1.1 state changed to 4
converse.min.js:244 removing request
converse.min.js:244 _throttledRequestHandler called with 0 requests
converse.min.js:244 request id 1 should now be removed
converse.min.js:244 request id 1.1 got 200
converse.min.js:244 _connect_cb was called
converse.min.js:244 <body xmlns="http://jabber.org/protocol/httpbind" xmlns:stream="http://etherx.jabber.org/streams" from="ip-172-31-32-69.us-west-2.compute.internal" authid="3lypbvh6k1" sid="3lypbvh6k1" secure="true" requests="2" inactivity="30" polling="5" wait="60" hold="1" ack="153712195" maxpause="300" ver="1.6"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism><mechanism>CRAM-MD5</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><register xmlns="http://jabber.org/features/iq-register"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features></body>
converse.min.js:244 _throttledRequestHandler called with 0 requests
converse.min.js:244 _throttledRequestHandler called with 1 requests
converse.min.js:244 request id 2.0 posting
converse.min.js:244 request id 2.0 state changed to 1
converse.min.js:244 <body rid="153712196" xmlns="http://jabber.org/protocol/httpbind" sid="3lypbvh6k1"><auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="EXTERNAL">dXNlckBpcC0xNzItMzEtMzItNjkudXMtd2VzdC0yLmNvbXB1dGUuaW50ZXJuYWw=</auth></body>
converse.min.js:244 request id 2.1 state changed to 2
converse.min.js:244 request id 2.1 state changed to 3
converse.min.js:243 XHR finished loading: POST "https://ec2-54-213-237-72.us-west-2.compute.amazonaws.com:7443/http-bind/".
c @ converse.min.js:243
_processRequest @ converse.min.js:243
_throttledRequestHandler @ converse.min.js:243
_onIdle @ converse.min.js:242
_onIdle @ converse.min.js:242
(anonymous) @ converse.min.js:243
converse.min.js:244 request id 2.1 state changed to 4
converse.min.js:244 removing request
converse.min.js:244 _throttledRequestHandler called with 0 requests
converse.min.js:244 request id 2 should now be removed
converse.min.js:244 request id 2.1 got 200
converse.min.js:244 _dataRecv called
converse.min.js:244 <body xmlns="http://jabber.org/protocol/httpbind" ack="153712196"><failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure></body>
converse.min.js:244 Status changed to: AUTHFAIL
converse.min.js:244 Status changed to: DISCONNECTING
converse.min.js:244 Disconnect was called because: Не удалось авторизоваться
converse.min.js:244 _sendTerminate was called
converse.min.js:244 _throttledRequestHandler called with 1 requests
converse.min.js:244 request id 3.0 posting
converse.min.js:244 request id 3.0 state changed to 1
converse.min.js:244 <body rid="153712197" xmlns="http://jabber.org/protocol/httpbind" sid="3lypbvh6k1" type="terminate"/>
converse.min.js:244 request id 3.1 state changed to 2
converse.min.js:244 request id 3.1 state changed to 3
converse.min.js:243 XHR finished loading: POST "https://ec2-54-213-237-72.us-west-2.compute.amazonaws.com:7443/http-bind/".
c @ converse.min.js:243
_processRequest @ converse.min.js:243
_throttledRequestHandler @ converse.min.js:243
_sendTerminate @ converse.min.js:243
_disconnect @ converse.min.js:242
disconnect @ converse.min.js:242
onConnectStatusChanged @ converse.min.js:245
_changeConnectStatus @ converse.min.js:242
_sasl_failure_cb @ converse.min.js:242
run @ converse.min.js:242
(anonymous) @ converse.min.js:242
forEachChild @ converse.min.js:241
_dataRecv @ converse.min.js:242
_onRequestStateChange @ converse.min.js:243
converse.min.js:244 request id 3.1 state changed to 4
converse.min.js:244 removing request
converse.min.js:244 _throttledRequestHandler called with 0 requests
converse.min.js:244 request id 3 should now be removed
converse.min.js:244 request id 3.1 got 200
converse.min.js:244 _dataRecv called
converse.min.js:244 <body xmlns="http://jabber.org/protocol/httpbind" type="terminate" ack="153712197"/>
converse.min.js:244 _doDisconnect was called
converse.min.js:244 Status changed to: DISCONNECTED
converse.min.js:244 DISCONNECTED

```

please help me to login user

**Comment by jcbrand** [comment] 2017-01-11 13:52
This is a duplicate of #751, check for the solution there.

**Closed by jcbrand** 2017-01-11 13:52 UTC
