### ISSUE TITLE
auto_reconnect does not work as expected

### ISSUE THREAD

**Issue by gpadbidri** [jcbrand/converse.js#333] opened 2015-03-11 16:49 UTC
Hi JC,

I have the <code>auto_reconnect : true</code> in my <code>converse.initialize</code> However, it fails when reconnect actually happens...

Following is the Test Case : 
1. Login to the Web Client.
2.Stay idle for some time...We see the <code>this.onConnect => <b>converse.reconnect();</b></code> gets invoked.
3. Reconnect happens but XMPP Server shows the user as offline. Also, other users trying to ping this user see him offline. This means the presence is NOT sent.

Where in the converse code is the right place to send the presence ? Ideally, reconnecting should also keep the User State as Online, right ?

NOTE : I have not modified any code that can impact this behavior.

**Comment by jcbrand** [comment] 2015-03-12 11:56
Related:  #330

**Comment by jcbrand** [comment] 2015-03-12 11:57
I don't know if it's so simple as that a presence is not sent, I think the problem is more that the strophe connection is not properly torn down. I'm not sure what the solution is, I'd have to investigate more deeply to get an idea of what the issue is.

**Comment by jcbrand** [comment] 2015-03-21 22:45
@gpadbidri Can you please see whether reconnecting now works for you? You'll need to specify ``prebind`` and  ``prebind_url``.

**Comment by jcbrand** [comment] 2015-04-08 10:29
I'm assuming it's fixed now.

**Comment by gauripadbidri** [comment] 2015-06-15 14:32
@jcbrand : I have exposed a prebind_url which returns me the JID, SID and <b>RID (Incrememnted by 1)</b>in response...I have also set auto_reconnect:true in my converse.initializ call...But, seems like the connection is established, but the Contacts Panel does NOT get refreshed, meaning : 


1. Assume User1 has logged in and sees User2 and User 3 logged in (Online Icon)
2. I restart the XMPP Server, now this.onConnect gets called and the ELSE PART gets invoked : 

<code>
if  ((typeof reconnect !== 'undefined') && (reconnect)) {
                    converse.log(status === Strophe.Status.CONNECTED ? 'Reconnected' : 'Reattached');
                    converse.onReconnected();
                } else {
                    converse.log(status === Strophe.Status.CONNECTED ? 'Connected' : 'Attached');
                    converse.onConnected();			
                }
</code>

<b>NOTE : Ideally, the IF Part should have gotten called as it is reconnect after Step #2</b>
3. I see a new connection established...<b>However, Contacts Panel still shows User 2 and User 3 as ONLINE, when they are offline.</b> 
4. Looking at 3, means the roster is NOT initialized.
5. Refreshing the Page displays User 2 and User 3 as OFFLINE - Expected (as restarting XMPP disconnected User 2 and User 3...Hence they seem offline)


Can you help me figure out what could have gone wrong ? Thanks !

**Comment by jcbrand** [comment] 2015-06-15 15:31
Please try to figure out why the first part of the `if` statement didn't execute. What is the value of `reconnect`? That appears to be a bug.

**Comment by gauripadbidri** [comment] 2015-06-15 15:36
It is ‘undefined’…this.onConnect is invoked from StartNewBOSHSession where we are NOT setting any value for reconnect parameter. Also, even if I do some code hack (likesetting a GLOBAL Flag demoFlag = true;) in the onSucess of startNewBoshSession and check it within the onConnect as follows : 

 

if (demoFlag === true || ((typeof reconnect !== 'undefined') && (reconnect))) {

                    converse.log(status === Strophe.Status.CONNECTED ? 'Reconnected' : 'Reattached');

                    jQuery(".controlbox-panes").css('position','absolute');

                    jQuery(".controlbox-panes").css('bottom','0px');

                    converse.onReconnected();

                } else {

                    converse.log(status === Strophe.Status.CONNECTED ? 'Connected' : 'Attached');

                    converse.onConnected();

                                                

                }

 

In the above case,the IF part is executed meaning reconnect happens, but still the issue remains.

**Comment by gauripadbidri** [comment] 2015-06-17 11:15
@jcbrand : Any updates on this issue ?

**Comment by gauripadbidri** [comment] 2015-06-17 11:29
@jcbrand : Also, setting "auto_reconnect" to true, should ideally keep polling the XMPP Server until the XMPP Server is UP ? I am not sure if the current code does that ? It just fires the reconnect event once and if the PREBIND URL was unable to send the JID SID and RID in response, it will delete the connection....

**Comment by jcbrand** [comment] 2015-06-17 14:18
Yes, it's clear the reconnection can still be improved.

**Comment by jcbrand** [comment] 2015-06-17 14:19
Please create 2 new tickets.

One for the status of contacts not being shown properly after reconnecting (you say they were wrongly shown as "online") and one for polling the server when reconnecting.

**Closed by jcbrand** 2015-06-17 14:18 UTC
Labels: bug
