### ISSUE TITLE
Invite to chat function for convert private chat to multi-user MUC

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#886] opened 2017-05-26 13:09 UTC
Very useful function in popular IM is invite third person to current chat, so convert private 2-person chat to multi-user chat. 

At now we must manually create new room in conference, take some name, and invite all users manually.
Will be good if we can do this via one action from private chat window - click "Invite to chat" button in private chat window, select contact, and continue talking already in MUC.

In XMPP this is not so easy to do - technically we must create MUC conference (with random id and name) and add three contacts to it.

But some Jabber clients already implement this, for example - in Conversations android client I can click "Invite" on any private chat and app will seamlessly convert it to MUC.

Will be good to see same behavior in converse.js jabber client too!

**Comment by jcbrand** [comment] 2017-05-31 06:49
This is a duplicate of #321

**Closed by jcbrand** 2017-05-31 06:49 UTC
