### ISSUE TITLE
Prebind doesnt load roster on first page load, but starts to work perfectly after refresh

### ISSUE THREAD

**Issue by pmkaboo** [jcbrand/converse.js#512] opened 2015-11-06 11:05 UTC
hello, 
im trying to setup converse with prebind and keepalive in rails app, but ive got stuck on a weird problem, on the first page load converse doesnt load the roster and is unable to receive/send messages, but it does send out presence status. after refreshing the page everything starts to work perfectly.

ive tried using multiple public jabber servers, last one yax.im, my bosh connection manager is punjab, i had this same problem with converse 0.9.6 and it persists with 0.10.0.

heres my converse initialisation code:
```javascript
require(['converse'], function (converse) {
    converse.initialize({
        debug: true,
        bosh_service_url: 'http://localhost:5280/http-bind',
        show_controlbox_by_default: true,
        allow_logout: false,
        authentication: 'prebind',
        keepalive: true,
        prebind_url: '/get_bosh_session',
        jid: <%= User.current.jabber_id %>,
        storage: 'session',
        message_carbons: true,
        message_archiving: 'always',
        use_vcard: 'false'
    });
});
```

heres the code @ prebind_url:
```ruby
def get_bosh_session
  require 'xmpp4r/httpbinding/client'
  jid = "#{User.current.jabber_id}/#{Time.now.to_s(:number)}"
  client = Jabber::HTTPBinding::Client.new(jid)
  client.connect('http://localhost:5280/http-bind')
  client.auth(User.current.jabber_password)
  sid = client.instance_variable_get('@http_sid')
  rid = client.instance_variable_get('@http_rid')
  render json: {jid: jid, sid: sid, rid: rid}
end
```

browser console output on first page load:
```
Could not restore session for jid: pmkaboo@yax.im Error message: _restore: no restoreable session.
converse.min.js:237 Status changed to: ATTACHED
converse.min.js:237 Attached
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 1.0 posting
converse.min.js:237 0 request id 1.0 state changed to 1
converse.min.js:237 <body rid=​"10612" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"yax.im" type=​"get" xmlns=​"jabber:​client" id=​"e024f331-fdfc-47ae-bb5d-bf785e69b29f:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​</query>​</iq>​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"yax.im" type=​"get" xmlns=​"jabber:​client" id=​"8621434e-ba36-4169-bf74-9979128a5887:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#items">​</query>​</iq>​<iq from=​"pmkaboo@yax.im/​20151106111246" id=​"enablecarbons" type=​"set" xmlns=​"jabber:​client">​<enable xmlns=​"urn:​xmpp:​carbons:​2">​</enable>​</iq>​<iq type=​"get" id=​"6e91bde4-d8db-4b19-98ba-f79d617a7175:​roster" xmlns=​"jabber:​client">​<query xmlns=​"jabber:​iq:​roster">​</query>​</iq>​</body>​
converse.min.js:237 0 request id 1.1 state changed to 2
converse.min.js:237 0 request id 1.1 state changed to 3
converse.min.js:237 0 request id 1.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 1 should now be removed
converse.min.js:237 0 request id 1.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"12919">​</iq>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
- only blank requests repeat from here
```

browser console output after refresh:
```
Status changed to: ATTACHED
converse.min.js:237 Attached
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 1.0 posting
converse.min.js:237 0 request id 1.0 state changed to 1
converse.min.js:237 <body rid=​"10619" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"yax.im" type=​"get" xmlns=​"jabber:​client" id=​"23731e2d-58ad-46f5-a3f9-0e2e064ff51a:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​</query>​</iq>​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"yax.im" type=​"get" xmlns=​"jabber:​client" id=​"baf36bcf-8c30-4029-a545-6efe3321aba4:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#items">​</query>​</iq>​<iq from=​"pmkaboo@yax.im/​20151106111246" id=​"enablecarbons" type=​"set" xmlns=​"jabber:​client">​<enable xmlns=​"urn:​xmpp:​carbons:​2">​</enable>​</iq>​<iq type=​"get" id=​"19c11aa2-73d3-42c8-aaa3-346a52e47e1f:​roster" xmlns=​"jabber:​client">​<query xmlns=​"jabber:​iq:​roster">​</query>​</iq>​</body>​
converse.min.js:237 0 request id 1.1 state changed to 2
converse.min.js:237 0 request id 1.1 state changed to 3
converse.min.js:237 0 request id 1.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 1 should now be removed
converse.min.js:237 0 request id 1.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"23731e2d-58ad-46f5-a3f9-0e2e064ff51a:​sendIQ" from=​"yax.im">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​<identity category=​"server" type=​"im" name=​"Prosody">​</identity>​<identity category=​"pubsub" type=​"pep" name=​"Prosody">​</identity>​<feature var=​"http:​/​/​jabber.org/​protocol/​commands">​</feature>​<feature var=​"urn:​xmpp:​ping">​</feature>​<feature var=​"msgoffline">​</feature>​<feature var=​"jabber:​iq:​last">​</feature>​<feature var=​"urn:​xmpp:​carbons:​2">​</feature>​<feature var=​"urn:​xmpp:​carbons:​1">​</feature>​<feature var=​"jabber:​iq:​register">​</feature>​<feature var=​"jabber:​iq:​roster">​</feature>​<feature var=​"urn:​xmpp:​time">​</feature>​<feature var=​"jabber:​iq:​time">​</feature>​<feature var=​"jabber:​iq:​private">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​disco#info">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​disco#items">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​pubsub#publish">​</feature>​<feature var=​"vcard-temp">​</feature>​<feature var=​"jabber:​iq:​privacy">​</feature>​<feature var=​"jabber:​iq:​version">​</feature>​</query>​</iq>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 2.0 posting
converse.min.js:237 0 request id 2.0 state changed to 1
converse.min.js:237 <body rid=​"10620" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
converse.min.js:237 0 request id 2.1 state changed to 2
converse.min.js:237 0 request id 2.1 state changed to 3
converse.min.js:237 0 request id 2.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 2 should now be removed
converse.min.js:237 0 request id 2.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​…​</body>​
2converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 Message carbons have been enabled.
2converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 GET http://localhost:3000/plugin_assets/easy_converse/fonticons/fonts/icomoon.woff?-mnoxh0 p.each.p.cssHooks.(anonymous function).get @ converse.min.js:237p.extend.css @ converse.min.js:237Yt.propHooks._default.get @ converse.min.js:237Yt.cur @ converse.min.js:237Yt.init @ converse.min.js:237Yt @ converse.min.js:237u.promise.createTween @ converse.min.js:237on.* @ converse.min.js:237fn @ converse.min.js:237ln @ converse.min.js:237hn @ converse.min.js:237p.fn.extend.animate.o @ converse.min.js:237p.extend.dequeue @ converse.min.js:237(anonymous function) @ converse.min.js:237p.extend.each @ converse.min.js:237p.fn.p.each @ converse.min.js:237p.fn.extend.queue @ converse.min.js:237p.fn.extend.animate @ converse.min.js:237p.each.p.fn.(anonymous function) @ converse.min.js:237(anonymous function) @ converse.min.js:237p.speed.r.complete @ converse.min.js:237p.Callbacks.f @ converse.min.js:237p.Callbacks.l.add @ converse.min.js:237hn @ converse.min.js:237p.fn.extend.animate.o @ converse.min.js:237p.extend.dequeue @ converse.min.js:237(anonymous function) @ converse.min.js:237p.extend.each @ converse.min.js:237p.fn.p.each @ converse.min.js:237p.fn.extend.queue @ converse.min.js:237p.fn.extend.animate @ converse.min.js:237p.each.p.fn.(anonymous function) @ converse.min.js:237d.initialize.ControlBoxToggle.Backbone.View.extend.hide @ converse.min.js:237d.initialize.ControlBoxView.m.ChatBoxView.extend.show @ converse.min.js:237d.initialize.ControlBoxView.m.ChatBoxView.extend.initialize @ converse.min.js:237t.View @ converse.min.js:237n.has.i @ converse.min.js:237n.has.i @ converse.min.js:237d.initialize.ChatBoxViews.Backbone.Overview.extend.onChatBoxAdded @ converse.min.js:237h @ converse.min.js:237t.Events.trigger @ converse.min.js:237n.extend._onModelEvent @ converse.min.js:237h @ converse.min.js:237t.Events.trigger @ converse.min.js:237n.extend.set @ converse.min.js:237n.extend.fetch.e.success @ converse.min.js:237e.BrowserStorage.sync.e.localSync @ converse.min.js:237e.sync @ converse.min.js:237n.extend.sync @ converse.min.js:237n.extend.fetch @ converse.min.js:237d.initialize.ChatBoxes.Backbone.Collection.extend.onConnected @ converse.min.js:237(anonymous function) @ converse.min.js:237t.error @ converse.min.js:237e.BrowserStorage.sync.e.localSync @ converse.min.js:237e.sync @ converse.min.js:237n.extend.sync @ converse.min.js:237n.extend.fetch @ converse.min.js:237d.initialize.initStatus @ converse.min.js:237d.initialize.onConnected @ converse.min.js:237d.initialize.onConnectStatusChanged @ converse.min.js:237r.Connection._changeConnectStatus @ converse.min.js:237e.Bosh._attach @ converse.min.js:237e.Bosh._restore @ converse.min.js:237r.Connection.restore @ converse.min.js:237d.initialize.attemptPreboundSession @ converse.min.js:237d.initialize.initConnection @ converse.min.js:237d.initialize._initialize @ converse.min.js:237d.initialize @ converse.min.js:237b.initialize @ converse.min.js:237(anonymous function) @ (index):156m.Callbacks.j @ jquery-1.11.1-ui-1.11.0-ujs-3.1.3.js:2m.Callbacks.k.fireWith @ jquery-1.11.1-ui-1.11.0-ujs-3.1.3.js:2x @ jquery-1.11.1-ui-1.11.0-ujs-3.1.3.js:4m.ajaxTransport.send.b @ jquery-1.11.1-ui-1.11.0-ujs-3.1.3.js:4
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 3.0 posting
converse.min.js:237 0 request id 3.0 state changed to 1
converse.min.js:237 <body rid=​"10621" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"anon.yax.im" type=​"get" xmlns=​"jabber:​client" id=​"11d69b1a-9e00-4e1b-80ef-5a8b004b3a2b:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​</query>​</iq>​<iq from=​"pmkaboo@yax.im/​20151106111246" to=​"chat.yax.im" type=​"get" xmlns=​"jabber:​client" id=​"e500b896-3cdf-4bac-89d8-058f43125e4d:​sendIQ">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​</query>​</iq>​<iq type=​"get" to=​"wtfkaboo@wtfismyip.com" xmlns=​"jabber:​client" id=​"27d1b4a7-df9f-4f03-abf8-bf2d9d3d33ad:​sendIQ">​<vcard xmlns=​"vcard-temp">​</vcard>​</iq>​<iq type=​"get" to=​"pmkaboo@jabbim.cz" xmlns=​"jabber:​client" id=​"99a0d5f3-f1d8-493e-96c5-60f958259421:​sendIQ">​<vcard xmlns=​"vcard-temp">​</vcard>​</iq>​<presence xmlns=​"jabber:​client">​</presence>​</body>​
converse.min.js:237 0 request id 3.1 state changed to 2
converse.min.js:237 0 request id 3.1 state changed to 3
converse.min.js:237 0 request id 3.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 3 should now be removed
converse.min.js:237 0 request id 3.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"11d69b1a-9e00-4e1b-80ef-5a8b004b3a2b:​sendIQ" from=​"anon.yax.im">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​<identity category=​"pubsub" type=​"pep" name=​"Prosody">​</identity>​<identity category=​"server" type=​"im" name=​"Prosody">​</identity>​<feature var=​"http:​/​/​jabber.org/​protocol/​commands">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​pubsub#publish">​</feature>​<feature var=​"msgoffline">​</feature>​<feature var=​"jabber:​iq:​version">​</feature>​<feature var=​"jabber:​iq:​privacy">​</feature>​<feature var=​"urn:​xmpp:​carbons:​2">​</feature>​<feature var=​"urn:​xmpp:​carbons:​1">​</feature>​<feature var=​"jabber:​iq:​register">​</feature>​<feature var=​"jabber:​iq:​roster">​</feature>​<feature var=​"urn:​xmpp:​time">​</feature>​<feature var=​"jabber:​iq:​time">​</feature>​<feature var=​"jabber:​iq:​private">​</feature>​<feature var=​"urn:​xmpp:​ping">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​disco#info">​</feature>​<feature var=​"http:​/​/​jabber.org/​protocol/​disco#items">​</feature>​<feature var=​"vcard-temp">​</feature>​<feature var=​"jabber:​iq:​last">​</feature>​</query>​</iq>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 4.0 posting
converse.min.js:237 0 request id 4.0 state changed to 1
converse.min.js:237 <body rid=​"10622" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
converse.min.js:237 0 request id 4.1 state changed to 2
converse.min.js:237 0 request id 4.1 state changed to 3
converse.min.js:237 0 request id 4.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 4 should now be removed
converse.min.js:237 0 request id 4.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"e500b896-3cdf-4bac-89d8-058f43125e4d:​sendIQ" from=​"chat.yax.im">​<query xmlns=​"http:​/​/​jabber.org/​protocol/​disco#info">​…​</query>​</iq>​<presence xmlns=​"jabber:​client" from=​"pmkaboo@yax.im/​20151106111246">​</presence>​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"99a0d5f3-f1d8-493e-96c5-60f958259421:​sendIQ" from=​"pmkaboo@jabbim.cz">​</iq>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 5.0 posting
converse.min.js:237 0 request id 5.0 state changed to 1
converse.min.js:237 <body rid=​"10623" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
converse.min.js:237 0 request id 5.1 state changed to 2
converse.min.js:237 0 request id 5.1 state changed to 3
converse.min.js:237 0 request id 5.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 5 should now be removed
converse.min.js:237 0 request id 5.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<presence xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" from=​"wtfkaboo@wtfismyip.com/​kaboo-pc-3">​<c xmlns=​"http:​/​/​jabber.org/​protocol/​caps" node=​"http:​/​/​pidgin.im/​" ver=​"DdnydQG7RGhP9E3k9Sf+b+bF0zo=" hash=​"sha-1">​</c>​<x xmlns=​"vcard-temp:​x:​update">​<photo>​f47d1f55673c702f6ce8e256c78f6037d74a6c43​</photo>​</x>​<delay xmlns=​"urn:​xmpp:​delay" stamp=​"2015-11-06T08:​45:​11.070Z" from=​"wtfkaboo@wtfismyip.com/​kaboo-pc-3">​</delay>​</presence>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 6.0 posting
converse.min.js:237 0 request id 6.0 state changed to 1
converse.min.js:237 <body rid=​"10624" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
:3000/plugin_assets/easy_converse/fonticons/fonts/icomoon.ttf?-mnoxh0:1 GET http://localhost:3000/plugin_assets/easy_converse/fonticons/fonts/icomoon.ttf?-mnoxh0 
converse.min.js:237 0 request id 6.1 state changed to 2
converse.min.js:237 0 request id 6.1 state changed to 3
converse.min.js:237 0 request id 6.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 6 should now be removed
converse.min.js:237 0 request id 6.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 7.0 posting
converse.min.js:237 0 request id 7.0 state changed to 1
converse.min.js:237 <body rid=​"10625" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
converse.min.js:237 0 request id 7.1 state changed to 2
converse.min.js:237 0 request id 7.1 state changed to 3
converse.min.js:237 0 request id 7.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 7 should now be removed
converse.min.js:237 0 request id 7.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
converse.min.js:237 0 _throttledRequestHandler called with 1 requests
converse.min.js:237 0 request id 8.0 posting
converse.min.js:237 0 request id 8.0 state changed to 1
converse.min.js:237 <body rid=​"10626" xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind" sid=​"3e7433984aeb62810a4b84e62553de7ea8454349">​</body>​
converse.min.js:237 0 request id 8.1 state changed to 2
2converse.min.js:237 0 request id 8.1 state changed to 3
converse.min.js:237 0 request id 8.1 state changed to 4
converse.min.js:237 0 removing request
converse.min.js:237 0 _throttledRequestHandler called with 0 requests
converse.min.js:237 0 request id 8 should now be removed
converse.min.js:237 0 request id 8.1 got 200
converse.min.js:237 1 _dataRecv called
converse.min.js:237 <body xmlns=​"http:​/​/​jabber.org/​protocol/​httpbind">​<iq xmlns=​"jabber:​client" to=​"pmkaboo@yax.im/​20151106111246" type=​"result" id=​"27d1b4a7-df9f-4f03-abf8-bf2d9d3d33ad:​sendIQ" from=​"wtfkaboo@wtfismyip.com">​<vCard xmlns=​"vcard-temp" version=​"2.0" prodid=​"-/​/​HandGen/​/​NONSGML vGen v1.0/​/​EN">​<PHOTO>​<TYPE>​image/png​</TYPE>​<BINVAL>...</BINVAL>​</PHOTO>​</vCard>​</iq>​</body>​
converse.min.js:237 1 no requests during idle cycle, sending blank request
- only blank requests repeat from here
```

ive also tried it without prebind_url:
```javascript
require(['converse'], function (converse) {
    $.getJSON('/get_bosh_session', function(data) {
        converse.initialize({
            debug: true,
            bosh_service_url: 'http://localhost:5280/http-bind',
            show_controlbox_by_default: true,
            allow_logout: false,
            authentication: 'prebind',
            keepalive: true,
            jid: <%= User.current.jabber_id %>,
            sid: data.sid,
            rid: data.rid,
            storage: 'session',
            message_carbons: true,
            message_archiving: 'always',
            use_vcard: 'false'
        });
    });
});
```
but in this case it doesnt do anything at all, on first load or after refreshing the page, console output just says that it couldnt restore session for my jid:
```
Could not restore session for jid: pmkaboo@yax.im Error message: _restore: no restoreable session.
```

**Comment by jcbrand** [comment] 2015-11-09 09:41
Sorry, but I don't know what the problem is here. I looked at the output you pasted but I don't see anything that points towards the problem.

Best you can do is to make sure to load the unminified source code and then to step through the source with the debugger.

You an also try to set up your own XMPP server and then check its logs when using converse.js.

I'm going to close this issue, because it's not clear that there is a bug here and the issue tracker is not for providing support. If you find a bug, you can open a new issue for it. You can also provide more info here if you find it, but I can't guarantee a timely response.

**Closed by jcbrand** 2015-11-09 09:41 UTC
