### ISSUE TITLE
converse.user.status.set(status) doesn't send presence over network

### ISSUE THREAD

**Issue by Juleffel** [jcbrand/converse.js#627] opened 2016-04-04 21:05 UTC
I'm running on the last release (0.10.1) of the code and haven't tested with the master branch, but found nothing in the issues so, here is my problem:

When I use the function converse.user.status.set(status) from the API, I see nothing else than blank pings (jid) passing on the network, and my status isn't updated for the other users. On the other side, when I use the dropdown, it works correctly, presence is sent and my status updated for others.

Browser: Firefox 45.0 under Ubuntu 15.10. I use a prebind_url for authentication and auto logon. (I run all my tests on the same computer, two different browser windows).

Updating status seems also to be the only way for me to force the server to take me in account. When I logon, I see other users connected, but they don't see me and I don't see their change of status. Once I have changed my status manually at least one time, they see me, my status, and I see their status changes. That could be a part of the problem.

Is this a known problem ? I can provide you more information if necessary.

**Comment by jcbrand** [comment] 2016-04-09 10:45
> Updating status seems also to be the only way for me to force the server to take me in account. When I logon, I see other users connected, but they don't see me and I don't see their change of status. Once I have changed my status manually at least one time, they see me, my status, and I see their status changes. That could be a part of the problem.

This is definitely not normal behavior. Normally converse.js should automatically send out a presence stanza the first time you log in (so that you don't have to do it manually).

Converse.js won't send out an initial presence if `send_initial_presence` is `false`. But it only ever gets set to false if you're attaching to a restored session, which is what happens when you have `keepalive` set to `true` and then reload the page. In other words, we don't want to send out the presence for each page load, it's not necessary.

What you can do is put breakpoints at these lines: 
https://github.com/jcbrand/converse.js/blob/v0.10.1/converse.js#L4976
https://github.com/jcbrand/converse.js/blob/v0.10.1/converse.js#L4984

And see if the presence gets sent out.

Concerning the issue of ` converse.user.status.set(status)` not working. I have no idea what the cause might be there. I'll have to look some time whether it gives me problems when I call it (AFAIK I don't call that API method in any of my code).

**Comment by Juleffel** [comment] 2016-04-17 17:54
Hi again,
I tried to put the keepalive to false, adding the sid and rid in my parameters, but the problem isn't fixed, I still need to change my status to receive status updates.
I will now try to use the non-minified code and add the breakpoints where you pointed to, and see what happen there.

I also put you here the requests and responses I see in firefox. It's interesting as my "presence" seems to be sent when I connect, but it's still after switching status that I receive status updates from my contacts. I don't really understand from which components the problem comes.

First request to http-bind:
`<body rid='357' xmlns='http://jabber.org/protocol/httpbind' sid='c67fd1d678f3c970889955f712789064246bb1b1'><iq from='juleffel@timemapstoryline.no-ip.info' id='enablecarbons' type='set' xmlns='jabber:client'><enable xmlns='urn:xmpp:carbons:2'/></iq><iq type='get' id='3b499a71-1778-4123-b9a3-11fafa7a37e0:roster' xmlns='jabber:client'><query xmlns='jabber:iq:roster'/></iq></body>`
->
`<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' type='result' id='session_120444'/></body>`

`<body rid='359' xmlns='http://jabber.org/protocol/httpbind' sid='c67fd1d678f3c970889955f712789064246bb1b1'><presence from='juleffel@timemapstoryline.no-ip.info' to='tmsl@conference-tmsl.no-ip.info/Juleffel' xmlns='jabber:client'><x xmlns='http://jabber.org/protocol/muc'><history/></x></presence><iq type='set' xmlns='jabber:client' id='e1766b9d-fbb6-412b-8605-08a2ab4e43e4:sendIQ'><query xmlns='jabber:iq:roster'><item jid='test2@timemapstoryline.no-ip.info' name='Test2'/></query></iq><iq type='set' xmlns='jabber:client' id='4a5aeeb2-d5a6-4558-9b1c-500abc4bf1f7:sendIQ'><query xmlns='jabber:iq:roster'><item jid='test@timemapstoryline.no-ip.info' name='Test'/></query></iq><iq type='set' xmlns='jabber:client' id='8176e909-23f7-4a3a-86b6-2fa7ff18773b:sendIQ'><query xmlns='jabber:iq:roster'><item jid='toto@timemapstoryline.no-ip.info' name='toto'/></query></iq><iq type='set' xmlns='jabber:client' id='a1ada51f-fb69-4c0e-8e90-740ccae50272:sendIQ'><query xmlns='jabber:iq:roster'><item jid='test1@timemapstoryline.no-ip.info' name='Test1'/></query></iq></body>`
->
`<body xmlns='http://jabber.org/protocol/httpbind'><presence xmlns='jabber:client' to='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05' from='tmsl@conference-tmsl.no-ip.info/Juleffel'><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='owner' jid='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05' role='moderator'/><status code='110'/></x></presence></body>`

Then comes also this, about vcards:
`<body rid='361' xmlns='http://jabber.org/protocol/httpbind' sid='c67fd1d678f3c970889955f712789064246bb1b1'><iq type='result' id='push11577964332953810558' from='juleffel@timemapstoryline.no-ip.info' xmlns='jabber:client'/><iq type='get' to='test2@timemapstoryline.no-ip.info' xmlns='jabber:client' id='5f09d9dc-a8da-4e98-965d-b278a1a552ca:sendIQ'><vCard xmlns='vcard-temp'/></iq><presence to='test2@timemapstoryline.no-ip.info' type='subscribe' xmlns='jabber:client'><nick>Juleffel</nick></presence><iq type='result' id='push8839654456566494611' from='juleffel@timemapstoryline.no-ip.info' xmlns='jabber:client'/><iq type='get' to='test@timemapstoryline.no-ip.info' xmlns='jabber:client' id='5ea688f5-e93f-418e-9f79-49236cbcecb3:sendIQ'><vCard xmlns='vcard-temp'/></iq><presence to='test@timemapstoryline.no-ip.info' type='subscribe' xmlns='jabber:client'><nick>Juleffel</nick></presence><iq type='result' id='push11522650065531328394' from='juleffel@timemapstoryline.no-ip.info' xmlns='jabber:client'/><iq type='get' to='toto@timemapstoryline.no-ip.info' xmlns='jabber:client' id='cbe8d4b7-5376-4821-b3d1-78ef90b4cc15:sendIQ'><vCard xmlns='vcard-temp'/></iq><presence to='toto@timemapstoryline.no-ip.info' type='subscribe' xmlns='jabber:client'><nick>Juleffel</nick></presence><iq type='result' id='push6858593411512966612' from='juleffel@timemapstoryline.no-ip.info' xmlns='jabber:client'/><iq type='get' to='test1@timemapstoryline.no-ip.info' xmlns='jabber:client' id='68f80ea4-6ad2-4901-998c-a2617831fdc1:sendIQ'><vCard xmlns='vcard-temp'/></iq><presence to='test1@timemapstoryline.no-ip.info' type='subscribe' xmlns='jabber:client'><nick>Juleffel</nick></presence></body>`
->
`<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' to='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05' from='test2@timemapstoryline.no-ip.info' id='5f09d9dc-a8da-4e98-965d-b278a1a552ca:sendIQ' type='result'><vCard xmlns='vcard-temp'><FN>Test2</FN><NICKNAME>Test2</NICKNAME><PHOTO><TYPE>JPEG</TYPE><BINVAL>/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAcFBQYFBAcGBQYIBwcIChELCgkJ ... iiipKP/9k=
</BINVAL></vCard></iq></body>`

Then a lot of blanks messages, even if I change status of other contacts.

Then, I change manually my status, and this is sent and received:
`<body rid='456' xmlns='http://jabber.org/protocol/httpbind' sid='c67fd1d678f3c970889955f712789064246bb1b1'><presence xmlns='jabber:client'><show>dnd</show></presence></body>`
->
`<body xmlns='http://jabber.org/protocol/httpbind'><presence xmlns='jabber:client' to='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05' from='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05'><show>dnd</show></presence></body>`

And the status update from the other account comes in:

`<body rid='457' xmlns='http://jabber.org/protocol/httpbind' sid='c67fd1d678f3c970889955f712789064246bb1b1'/>`
->
`<body xmlns='http://jabber.org/protocol/httpbind'><presence xmlns='jabber:client' to='juleffel@timemapstoryline.no-ip.info/bosh_o5sh05' from='test2@timemapstoryline.no-ip.info/bosh_o5sg1u'><show>dnd</show><delay xmlns='urn:xmpp:delay' stamp='2016-04-17T17:42:24.050Z' from='test2@timemapstoryline.no-ip.info/bosh_o5sg1u'/></presence></body>`

Thank you for your time and this wonderful project :) Apart from that point, it works perfectly fine !

**Comment by jcbrand** [comment] 2016-04-18 07:07
Hi, BTW what server are you using?

What you can try, is to automatically send out a presence stanza just after the page has loaded, to see if that fixes things.

Something like this:
```
converse.listen.on('ready', function (event) {
    converse.user.status.set('online');
});
```
More info here: https://conversejs.org/docs/html/development.html#the-status-sub-grouping

**Comment by Juleffel** [comment] 2016-04-18 17:55
I'm using a ejabberd server, with the conversejs bosh server, for the moment. I'm using this code for the prebind in ruby : https://github.com/mixxt/bosh4r/blob/master/lib/bosh4r/session.rb

In fact this hook (send presence via the status.set function) is what I tried first to solve the problem, and the reason of the issue. I retried to launch this function now I have set keepalive to false, and it still doesn't send anything on the network, though I see a changing status in the interface.

**Comment by jcbrand** [comment] 2016-04-19 13:37
> I retried to launch this function now I have set keepalive to false, and it still doesn't send anything on the network, though I see a changing status in the interface.

I see that in the 0.10.1 release it doesn't explicitly send out the presence stanza. In the master branch this is however the case.

You need to add this line inside that API method, to make sure the stanza is sent out.
https://github.com/jcbrand/converse.js/blob/master/src/converse-api.js#L56

`converse.xmppstatus.sendPresence(value);`

**Comment by Juleffel** [comment] 2016-05-01 18:33
Ok, I finally built converse from github master and integrated it into my app. The method " converse.user.status.set('online'); " now works, so I can send my first presence with this method.

However, all the rest still doesn't really works. My presence doesn't seems to be sent when I connect, and I receive status updates only after changing status.

I wrote a workaround to be sure to see my contacts and everythings works now, but it seems to be a very awful one. I added a function in the API: converse.user.status.sendPresence() which just call the xmpp function you talked about : 
`'sendPresence': function () {
    converse.xmppstatus.sendPresence();
},`

I call this function from my code every 5 seconds in a loop. I prefer to use this method because I don't want to send notification of status change every 5s. My contacts now appears in converse and I receive every updates, everywhere. It even seems to work with multiple tabs.. I don't know how bad it is to send presence every 5s, though, and if it's really necessary..

**Comment by jcbrand** [comment] 2016-05-02 06:26
That should really not be necessary. Normally the presence only needs to be sent once, after login, and then again whenever the user changes his presence status. This is all already handled by converse.js.

What does your `converse.initialize` call look like?

**Comment by jcbrand** [comment] 2016-06-03 05:48
This should be fixed now. I use this API method myself and confirmed that as a result a presence stanza gets sent out.

**Closed by jcbrand** 2016-06-03 05:48 UTC
