### ISSUE TITLE
Create web interface for view Jabber XEP-0313 mod_mam message archive in browser

### ISSUE THREAD

**Issue by MurzNN** [jcbrand/converse.js#731] opened 2016-11-16 06:22 UTC
At now Converse.js support loading archive of last messages via mod_mam XEP-0313 from Jabber server to message dialog, and this works well (on ejabberd server). This is good for look last dialog history, but not usable for searching old messages (via date or keyword).

Please provide full featured interface for view all archive messages, with filter by date, keywords.

**Comment by jcbrand** [comment] 2016-11-16 10:06
Duplicate of #631

**Closed by jcbrand** 2016-11-16 10:06 UTC
