### ISSUE TITLE
Auto reconnect with auto login

### ISSUE THREAD

**Issue by themaverick777** [jcbrand/converse.js#646] opened 2016-05-19 09:34 UTC
Hi JC, 

When using **auto_login**, **keepalive** and **auto_reconnect** set to **true** along with **jid** and **password**, in case of connection drop, I see the login spinner which spins indefinitely. Is it possible to have an auto login form with only a button that when pressed it will automatically reconnect, so in case the connection drops, we let the connection fail gracefully and notify the user, then the user will be able to reconnect again without having to fill the login form.

**Comment by jcbrand** [comment] 2016-05-19 09:37
If you are providing a jid and password, then converse.js will try to reconnect again using that same jid and password, so the user shouldn't have to press a button (as this will happen automatically).

If you only see the spinner and don't get logged in again, then the problem is with the reconnection and should be fixed there I think, and not by adding a button.

**Comment by themaverick777** [comment] 2016-05-19 09:55
Okay. But I mean after the 60 seconds disconnect timeout the spinner starts spinning indefinitely.

**Comment by jcbrand** [comment] 2016-05-19 10:52
I don't understand exactly what you mean by that.

**Closed** 2016-06-03 05:47 UTC
