### ISSUE TITLE
Scrollbar jumps

### ISSUE THREAD

**Issue by c143** [jcbrand/converse.js#352] opened 2015-03-26 10:18 UTC
When opening a new chat or closing one, the scrollbar of the other open chats jumps up. So you always have to scroll down.

And when closing a chat with existing messages and reopening it, the scrollbar is at the top, too. Should be at the bottom.

**Comment by pidupuis** [comment] 2015-04-08 08:42
If I may add something: when you manually scrolled up to read previous messages, any new message will bring your scrollbar at the bottom, preventing you to finish reading...

**Comment by jcbrand** [comment] 2015-06-22 17:02
@c143 I can't reproduce this problem on the master branch. I tried both Chrome and Firefox.

@pidupuis The fix for this would be to record the scroll position and only scroll down if it was at the bottom before a message was received. Will keep this ticket open for that fix.

**Comment by jcbrand** [comment] 2016-01-15 07:39
@pidupuis I wanted to fix this issue now, but eventually decided on a compromise. The chat window won't scroll down (when the user manually scrolled up) when a chat event notification (i.e. *Johnny is typing*) is shown.

However, I decided to still scroll down when an actual chat message is received. The main reason for this is that on MacOS the scrollbar is not visible by default. So I'm concerned that certain less savvy users might not notice that they're not at the bottom of the chat window and therefore not be aware when new messages are received.

There could be some UI solutions for this, like showing self-healing (Growl-like) messages, showing some indication in the chat window that there's more content below the visible area or adding HTML5 notifications. So eventually I might change the behavior if any of those features are implemented.

Two more reasons why I decided to keep it as is for now:
1. The window is resizable, so instead of scrolling up, the window can be made taller. (This of course doesn't help if the messages you want to read are too far up).
2. I also noticed that Adium always scrolls down when new messages are received.

I'll close this ticket for now, however this might be revisited in the future.

**Closed by jcbrand** 2016-01-15 07:39 UTC
Labels: bug
