### ISSUE TITLE
Fail to register on some ejabberd servers

### ISSUE THREAD

**Issue by mytbk** [jcbrand/converse.js#957] opened 2017-11-26 06:47 UTC
I fail to get a registration form on cnjabber.net or xmpp.jp. I got the following response from the Firefox development tools when using the conversejs.org webapp.

```
<body xmlns='http://jabber.org/protocol/httpbind'><iq xmlns='jabber:client' type='error'><query xmlns='jabber:iq:register'/><error code='400' type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>Missing attribute 'id' in tag &lt;iq/&gt; qualified by namespace 'jabber:client'</text></error></iq></body>
```

**Comment by jcbrand** [comment] 2017-12-18 11:19
This should already be fixed in master AFAIK.

**Comment by jcbrand** [comment] 2017-12-18 11:20
Also, it's a duplicate of #800

**Closed by jcbrand** 2017-12-18 11:20 UTC
