### ISSUE TITLE
Error when open index.html

### ISSUE THREAD

**Issue by docaohuynh** [jcbrand/converse.js#616] opened 2016-03-19 03:47 UTC
Dear Jcbrand!

I open index.html file but have error

```
TypeError: obj is undefined
if (!obj.prototype._super) {
```
In file 	
**converse.js** (line 28760, col 17)

**Comment by lixmal** [comment] 2016-03-19 13:08
It seems the value for key "MinimizedChatBoxView" is undefined in this line:

`                         this._extendObject(converse[key], override);`

**converse-core.js**, line 1840

**Comment by jcbrand** [comment] 2016-03-19 13:34
Thanks @lixmal, that helped me know what the problem is.

I've pushed a fix for this. Please update and check again.

**Comment by lixmal** [comment] 2016-03-19 14:01
Works for me, error is gone.
Thanks a lot.

**Closed** 2016-03-19 14:55 UTC
